genesis_id = ""
system = "KICKICO"
dependencies = ["Ethereum"]
icon = "kickico"

[token]
name = "KickCoin"
symbol = "KC"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "A unified blockchain-based platform for cryptocurrency crowdfunding"

[crowdsales]
start_date = "2017-08-29T13:00:00"
end_date = "2017-09-29T13:00:00"
end_date_plan = "2017-09-29T13:00:00"
genesis_address = [""]
funding_terms = "https://www.kickico.com/"
funding_url = "https://www.kickico.com/"
tokens_sold = ""
tokens_issued = 800000000
btc_raised = ""
cap_limit = ["eth = 200000"]
raised = [""]

[[links]]
type = "website"
name = "kickico.com"
url = "http://www.kickico.com"
tags = ["Main"]

[[links]]
type = "paper"
name = "Kickico Whitepaper"
url = "https://www.kickico.com/whitepaper"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Kickico Blog"
url = "https://medium.com/@kickico"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/KICKICOplatform"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Kickico Telegram"
url = "https://t.me/kickico"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/KickICO/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Kickico-1909910745919239"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UC_zMuXu_P7idt84qOqDFMcw"
icon = "youtube.png"
tags = ["News"]
