genesis_id = ""
system = "Brickblock"
dependencies = ["Ethereum"]
icon = "brickblock"

[token]
name = "brickblock token"
symbol = "BRICKBLOCK"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "The future of stock trading on the blockchain"

[crowdsales]
start_date = "2017-08-02T12:00:00"
end_date = "2017-08-06T23:59:00"
end_date_plan = "2017-08-06T23:59:00"
genesis_address = [""]
funding_terms = "https://blog.brickblock.io/brickblock-token-sale-812575df1e24"
funding_url = "https://brickblock.io"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "brickblock.io"
url = "https://www.brickblock.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Brickblock General Whitepaper"
url = "https://www.bancor.network/whitepaper/en"
tags = ["Main", "Science"]

[[links]]
type = "paper"
name = "Brickblock Technical Whitepaper"
url = "https://www.brickblock.io/files/Brickblock_Technical_Whitepaper_v093.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Brickblock GitHub"
url = "https://github.com/brickblock-io"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Brickblock Blog"
url = "https://blog.brickblock.io/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1966929"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/brickblock_io"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Brickblock Telegram"
url = "https://t.me/joinchat/AAAAAERj-_1p8AktrkESlQ"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Brickblock Slack"
url = "https://slack.brickblock.io/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/brickblock.io/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UC7etm1NmMFIlg2KJ6VXNNrA/videos"
icon = "youtube.png"
tags = ["News"]
