genesis_id = ""
system = "Neblio"
dependencies = ["independent"]
icon = "neblio"

[token]
name = "neblio token"
symbol = "NEBL"

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Next Generation Enterprise Blockchain Soultions"

[crowdsales]
start_date = "2017-08-05T22:00:00"
end_date = "2017-08-20T21:59:00"
end_date_plan = "2017-08-20T21:59:00"
genesis_address = [""]
funding_terms = "https://nebl.io/pre-sale/cart/neblio-pre-sale-terms-and-conditions/"
funding_url = "https://nebl.io/pre-sale/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "nebl.io"
url = "https://nebl.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Neblio Whitepaper"
url = "https://nebl.io/wp-content/uploads/2017/07/NeblioWhitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Neblio GitHub"
url = "https://github.com/NeblioTeam/neblio"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Neblio Blog"
url = "https://nebl.io/blog/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2048414.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/NeblioTeam"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Neblio Telegram"
url = "https://t.me/joinchat/GFVgzw5J4d4uwgXeKowRXg"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/neblioteam/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Neblio/"
icon = "reddit.png"
tags = ["News"]
