genesis_id = ""
system = "bitJob"
dependencies = ["Ethereum"]
icon = "bitjob"

[token]
name = "bitjob token"
symbol = "STU"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized Marketplace for Student Employment"

[crowdsales]
start_date = "2017-08-02T00:00:00"
end_date = "2017-10-13T00:00:00"
end_date_plan = "2017-10-13T00:00:00"
genesis_address = [""]
funding_terms = "https://bitjob.io/"
funding_url = "https://bitjob.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 200000000

[[links]]
type = "website"
name = "bitjob.io"
url = "https://bitjob.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "bitJob Whitepaper"
url = "https://drive.google.com/file/d/0B6VVmGzOdFPBSlBjZlhFaGJnbUk/view"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "bitJob GitHub"
url = "https://github.com/bitjobteam"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "bitJob Blog"
url = "https://medium.com/bitjob"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1980078.msg19714383#msg19714383"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/BitJob_Team"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "bitJob Telegram"
url = "https://t.me/bitjob"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "bitJob Slack"
url = "https://bit-job.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/bitJobmarket/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCPtjrCU8pUztqQHY75a7npg"
icon = "youtube.png"
tags = ["News"]
