
genesis_id = ""
system = "Rentberry"
dependencies = ["Ethereum"]
icon = "rentberry"

[token]
name = "rentberry token"
symbol = "BERRY"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized Home Rental Platform"

[crowdsales]
start_date = "2017-11-28T12:00:00"
end_date = "2018-01-01T12:00:00"
end_date_plan = "2018-01-01T12:00:00"
genesis_address = [""]
funding_terms = "https://ico.rentberry.com/"
funding_url = "https://ico.rentberry.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "ico.rentberry.com"
url = "https://ico.rentberry.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Rentberry Whitepaper"
url = "https://cdn.rentberry.com/ico/downloads/Rentberry_Whitepaper_V1_en.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Rentberry Github"
url = "https://github.com/Rentberry"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/rentberry_"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/RentberryInc/"
icon = "facebook.png"
tags = ["News"]
