genesis_id = ""
system = "Stable"
dependencies = ["Ethereum"]
icon = "stable"

[token]
name = "coss token"
symbol = "COSS"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Stabilizing digital tokens universe"

[crowdsales]
start_date = "2017-08-14T00:00:00"
end_date = "2017-09-10T00:00:00"
end_date_plan = "2017-09-10T00:00:00"
genesis_address = [""]
funding_terms = "https://stable.foundation/"
funding_url = "https://stable.foundation/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "stable.foundation"
url = "https://stable.foundation/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Stable Whitepaper"
url = "https://stable.foundation/wp-content/uploads/2017/07/stable_white_paper_v_0_96.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Stable GitHub"
url = "https://gist.github.com/stableproject/a5d86b94db7f62ebd0b2f1c286a23233"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/STABLE_token"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Stable-1532564000127095/"
icon = "facebook.png"
tags = ["News"]
