genesis_id = ""
system = "Opus"
dependencies = ["Ethereum"]
icon = "opus"

[token]
name = "opus token"
symbol = "OPT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized music sharing protocol"

[crowdsales]
start_date = "2017-07-23T00:00:00"
end_date = "2017-08-23T00:00:00"
end_date_plan = "2017-08-23T00:00:00"
genesis_address = [""]
funding_terms = "http://opus-foundation.org/"
funding_url = "http://opus-foundation.org/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "opus-foundation.org"
url = "http://opus-foundation.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Opus Whitepaper"
url = "http://opus-foundation.com/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Opus GitHub"
url = "https://github.com/Opus-foundation/contracts"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Opus Blog"
url = "https://opus-foundation.org/index.php/blog/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2011065.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/opusfoundation?lang=en"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/opusfoundation"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Opus Telegram"
url = "https://t.me/opusfoundation"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Opus Slack"
url = "http://slack.opus-foundation.org/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/opusfoundation/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCLXcTgzr05cFZaN972nuEXw"
icon = "youtube.png"
tags = ["News"]
