genesis_id = ""
system = "ZClassic"
dependencies = ["independent"]
icon = "zclassic"

[token]
name = "zclassic"
symbol = "ZCL"

[consensus]
consensus_type = "Proof-of-Work"
consensus_name = "Equihash"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Zero-knowledge Cryptocurrency"

[aliases]
coinmarketcap = "ZClassic"

[specs]
supply = ""

[flags]

[[links]]
type = "website"
name = "zclassic.org"
url = "http://zclassic.org/"
tags = ["Main"]

[[links]]
type = "github"
name = "ZClassic GitHub"
url = "https://github.com/z-classic/zclassic"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Blog"
url = ""
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://www.reddit.com/r/ZClassic/"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/ZclassicCoin"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "ZClassic Slack"
url = "http://zclassic.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/ZClassic/"
icon = "reddit.png"
tags = ["News"]
