genesis_id = ""
system = "Cindicator"
dependencies = ["Ethereum"]
icon = "cindicator"

[token]
name = "cindicator token"
symbol = "CND"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Hybrid Intelligence for asset management"

[crowdsales]
start_date = "2017-09-12T16:00:00"
end_date = "2017-10-12T16:00:00"
end_date_plan = "2017-10-12T16:00:00"
genesis_address = [""]
funding_terms = "https://cindicator.com"
funding_url = "https://cindicator.com"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "cindicator.com"
url = "https://cindicator.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Cindicator Whitepaper"
url = "https://cindicator.com/Cindicator_WhitePaper_en.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Cindicator GitHub"
url = "https://github.com/cindicator"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Cindicator Blog"
url = "https://medium.com/@Cindicator"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2062875"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/crowd_indicator"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Cindicator Telegram"
url = "https://t.me/cindicator_news"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Cindicator Slack"
url = "https://cindicator-community.slack.com/join/shared_invite/MjE5MDg2NzI5Mjg2LTE1MDExMDQzNTUtZjU4ZWRjNDlkNw"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Cindicator/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/crowdindicator"
icon = "facebook.png"
tags = ["News"]
