genesis_id = ""
system = "Fujinto"
dependencies = ["Ethereum"]
icon = "fujinto"

[token]
name = "fujinto token"
symbol = "NTO"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Cryptocurrency for Travel industry"

[crowdsales]
start_date = "2017-08-10T12:00:00"
end_date = "2017-09-10T12:00:00"
end_date_plan = "2017-09-10T12:00:00"
genesis_address = ["0x66dc70150c5A1B236D4856a234B79AC8b91Cfe1c"]
funding_terms = "http://fujinto.io/index.html"
funding_url = "http://fujinto.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 400000000

[[links]]
type = "website"
name = "fujinto.io"
url = "http://fujinto.io/index.html"
tags = ["Main"]

[[links]]
type = "paper"
name = "Fujinto Whitepaper"
url = "https://www.bancor.network/whitepaper/en"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Fujinto GitHub"
url = "https://github.com/fujinto/fujinto-smart-contract"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2077763.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/FUJINTO_"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Fujinto/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCwAGuFiY6wGXWIfOIZA8Qjg"
icon = "youtube.png"
tags = ["News"]
