genesis_id = ""
system = "Veritaseum"
dependencies = ["Ethereum"]
icon = "veritaseum"

[token]
name = "veritaseum coin"
symbol = "VERI"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "P2P Capital Markets Through Human Readable Smart Contracts"

[crowdsales]
start_date = "2017-04-25T09:30:00"
end_date = "2017-05-26T09:30:00"
end_date_plan = "2017-05-26T09:30:00"
genesis_address = [""]
funding_terms = "https://docs.google.com/presentation/d/1FMyNvogofqojqG6nkIjgvvjAnsWs1qOtKUFExvtp_m0/pub?start=false&loop=false&delayms=3000&slide=id.ga8c8a77e4_0179"
funding_url = "https://blog.veritaseum.com/current-analysis/1-blog/219-in-anticipation-of-veritaseum-s-ico-an-executive-summary-of-the-veritaseum-platform"
tokens_sold = ""
tokens_issued = 100000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "veritas.veritaseum.com"
url = "http://veritas.veritaseum.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Veritaseum Whitepaper"
url = "https://docs.google.com/presentation/d/1FMyNvogofqojqG6nkIjgvvjAnsWs1qOtKUFExvtp_m0/pub?start=false&loop=false&delayms=3000&slide=id.ga8c8a77e4_0179"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Veritaseum GitHub"
url = "https://github.com/veritaseum"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/ReggieMiddleton"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/reggiemiddletonfintech/?fref=ts"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCjVEF7ABJwyzw_8pb5frVmg"
icon = "youtube.png"
tags = ["News"]
