genesis_id = ""
system = "Indorse"
dependencies = ["Ethereum"]
icon = "indorse"

[token]
name = "indorse token"
symbol = "IND"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "utility"
headline = "Decentralized Professional Network on Ethereum Blockchain"

[crowdsales]
start_date = "2017-08-08T11:00:00"
end_date = "2017-09-07T11:00:00"
end_date_plan = "2017-09-08T11:00:00"
genesis_address = ["indorse.eth"]
funding_terms = "https://indorse.io"
funding_url = "https://indorse.io"
tokens_sold = ""
tokens_issued = 28288567.8
btc_raised = ""
cap_limit = [""]
raised = ["usd = 23689518"]

[[links]]
type = "website"
name = "indorse.io"
url = "https://indorse.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Indorse Whitepaper"
url = "https://indorse.io/whitepaper"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Indorse Blog"
url = "https://medium.com/joinindorse"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2047503.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Indorse Telegram"
url = "https://t.me/joinchat/AAAAAA1WIyLU_WrlA3b3zw"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/joinIndorse"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Indorse Slack"
url = "https://slack.indorse.io"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/JoinIndorse/"
icon = "facebook.png"
tags = ["News"]
