genesis_id = ""
system = "Starbase"
dependencies = ["Ethereum"]
icon = "starbase"

[token]
name = "star token"
symbol = "STAR"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Token-based crowdfunding system"

[crowdsales]
start_date = "2017-08-30T00:00:00"
end_date = "2017-10-14T23:59:00"
end_date_plan = "2017-10-14T23:59:00"
genesis_address = [""]
funding_terms = "https://starbase.co/crowdsale"
funding_url = "https://starbase.co/crowdsale"
tokens_sold = ""
tokens_issued = 0
btc_raised = ""
cap_limit = ["usd = 125000000"]
raised = [""]

[[links]]
type = "website"
name = "starbase.co"
url = "https://starbase.co/"
tags = ["Main"]

[[links]]
type = "paper"
name = "starbase Whitepaper"
url = "https://starbase.co/whitepaper"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Starbase GitHub"
url = "https://github.com/starbaseco"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Starbase Blog"
url = "https://blog.starbase.co/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1779533"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/JoberrCO"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Starbase Telegram"
url = "https://telegram.me/starbase"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Starbase Slack"
url = "https://starbase-community.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/joberr/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/StarbaseCo/"
icon = "facebook.png"
tags = ["News"]
