genesis_id = ""
system = "Sift"
dependencies = ["Ethereum"]
icon = "sift"

[token]
name = "sift token"
symbol = "SIFT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Crytpo Asset Investment and Trading Fund"

[crowdsales]
genesis_address = ["0xf8Fc0cc97d01A47E0Ba66B167B120A8A0DeAb949","0x8a187d5285d316bcbc9adafc08b51d70a0d8e000"]
funding_terms = "https://smartift.com/"
funding_url = "https://smartift.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "smartift.com"
url = "https://smartift.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Sift Whitepaper"
url = "https://smartift.com/sift_whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Sift GitHub"
url = "https://github.com/smartift"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/smartift"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Sift Telegram"
url = "https://t.me/smartift"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/SmartIFT/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCA125wWsdbsG1XPenWcBkyg"
icon = "youtube.png"
tags = ["News"]
