genesis_id = "0x960b236A07cf122663c4303350609A66A7B288C0"
system = "Aragon"
dependencies = ["Ethereum"]
icon = "aragon"

[token]
name = "aragon net token"
symbol = "ANT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Decentralized Infrastructure for DAOs"

[aliases]
coinmarketcap = "Aragon"

[crowdsales]
start_date = "2017-05-17T18:33:00"
end_date = "2017-05-17T19:00:00"
end_date_plan = "2017-06-14T17:00:00"
genesis_address = ["0x960b236a07cf122663c4303350609a66a7b288c0","0xcafe1a77e84698c83ca8931f54a755176ef75f2c"]
funding_terms = "https://blog.aragon.one/aragon-network-token-sale-terms-8998f63a3429"
funding_url = "https://aragon.one"
tokens_sold = 27726667
tokens_issued = 39609523.80952380954
btc_raised = 13703
cap_limit = ["ETH = 275000"]
raised = ["ETH = 275000"]

[specs]
supply = 39609523.80952380954

[first_price]
date = "2017-06-17T19:00:00"
usd = 0.88496531
btc = 0.00049420

[flags]
supply_from_here = true

[[links]]
type = "website"
name = "aragon.one"
url = "https://aragon.one"
tags = ["Main"]

[[links]]
type = "paper"
name = "Aragon Whitepaper"
url = "https://github.com/AragonOne/whitepaper/raw/master/Aragon%20Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "wallet"
name = "Aragon App"
url = "https://github.com/aragon"
icon = "aragon.png"
tags = ["Main","Apps","Wallet"]

[[links]]
type = "github"
name = "Aragon GitHub"
url = "https://github.com/aragon"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Aragon Blog"
url = "https://blog.aragon.one/"
icon = "medium.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/AragonProject"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Aragon Slack"
url = "https://aragon.chat/"
icon = "salck.png"
tags = ["News"]

[[links]]
type = "explorer"
name = "EtherChain.org"
url = "http://etherchain.org/"
icon = "etherchain.jpg"
tags = ["Apps", "Analytics"]

[[links]]
type = "explorer"
name = "EthereumWisdom"
url = "http://ethereumwisdom.com"
icon = "explorer.png"
tags = ["Apps", "Analytics"]

[[links]]
type = "explorer"
name = "Ether.Camp"
url = "http://frontier.ether.camp/"
icon = "ethercamp.png"
tags = ["Apps", "Analytics"]

[[links]]
type = "wallet"
name = "Ethereum Wallet"
url = "https://github.com/ethereum/mist/releases/"
icon = "ethereum.png"
tags = ["Main", "Apps", "Wallet"]

[[links]]
type = "wallet"
name = "Parity"
url = "https://parity.io/"
icon = "parity.png"
tags = ["Apps", "Wallet"]

[[links]]
type = "wallet"
name = "MyEther Wallet"
url = "https://www.myetherwallet.com/"
icon = "myetherwallet.png"
tags = ["Apps", "Wallet"]

[[links]]
type = "wallet"
name = "MetaMask"
url = "https://metamask.io/"
icon = "metamask.png"
tags = ["Apps", "Wallet"]

[[links]]
type = "exchange"
name = "Bittrex"
url = "https://bittrex.com"
icon = "bittrex.png"
tags = ["Apps", "Exchange"]
