genesis_id = ""
system = "TokenCard"
dependencies = ["Ethereum"]
icon = "tokencard"

[token]
name = "tokencard token"
symbol = "TKN"

[consensus]
consensus_type = "ERC20"
consensus_name = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Debit Card and Platform for Ethereum tokens"

[aliases]
coinmarketcap = "TokenCard"

[crowdsales]
start_date = "2017-05-02T16:00:00"
end_date = "2017-05-02T16:05:00"
end_date_plan = "2017-05-02T16:05:00"
genesis_address = ["0x49EdF201c1E139282643d5e7C6fB0C7219Ad1db7"]
funding_terms = "http://tokencard.io/TKNCreationTerms.pdf"
funding_url = "http://tokencard.io/"
tokens_sold = 23644056
tokens_issued = 39406760
btc_raised = 8644
cap_limit = ["usd = 21122842"]
raised = ["usd = 12673744"]

[first_price]
date = "2017-05-07T02:04:49"
usd = 0.5360207
btc = 0.0003656

[[links]]
type = "website"
name = "tokencard.io"
url = "https://tokencard.io/"
icon = "website.png"
tags = ["Main"]

[[links]]
type = "github"
name = "GitHub"
url = "https://github.com/MonolithDAO/token"
icon = "website.png"
tags = ["Main","Code"]

[[links]]
type = "paper"
name = "TokenCard Whitepaper"
url = "http://tokencard.io/tokencard_whitepaper.pdf"
icon = "paper.png"
tags = ["Main","News"]

[[links]]
type = "blog"
name = "Blog"
url = "https://medium.com/@MonolithStudio"
icon = "medium.png"
tags = ["Main","News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1840820.0"
icon = "btc.png"
tags = ["Main","News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/tokencard_io"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Telegram"
url = "https://t.me/TokenCard"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "reddit"
url = "https://www.reddit.com/r/ethereum/comments/5gtb7p/introducing_tokencard_the_ether_and_erc20/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Slack"
url = "https://tokencard-team.herokuapp.com/"
icon = "slack.png"
tags = ["News"]
