genesis_id = ""
system = "Moose Coin"
dependencies = ["Lisk"]
icon = "moosecoin"

[token]
name = "moose coin"
symbol = "MOOSE"

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralised organisation for musicians "

[crowdsales]
start_date = "2017-07-30T23:59:00"
end_date = "2017-09-30T23:59:00"
end_date_plan = "2017-09-30T23:59:00"
genesis_address = [""]
funding_terms = "https://www.moosecoin.io"
funding_url = "https://www.moosecoin.io"
tokens_sold = 165156.27840000
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "moosecoin.io"
url = "https://www.moosecoin.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Moose Coin Whitepaper"
url = "https://www.moosecoin.io/MooseCoin-Whitepaper-v0.0.2.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Moose Coin GitHub"
url = "https://github.com/Moosty"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/MoostyMusic"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Moose Coin Slack"
url = "https://moosecoin.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/moosecoin/"
icon = "reddit.png"
tags = ["News"]
