genesis_id = ""
system = "Round"
dependencies = ["Ethereum"]
icon = "round"

[token]
name = "round"
symbol = "ROUND"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized eSports Platform"

[aliases]
coinmarketcap = "Round"

[specs]
supply = ""

[flags]

[[links]]
type = "website"
name = "roundcoin.org"
url = "http://roundcoin.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Round Whitepaper"
url = "http://roundcoin.org/storage/white_paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "GitHub"
url = ""
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Blog"
url = ""
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1657439.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = ""
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Slack"
url = ""
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = ""
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = ""
icon = "youtube.png"
tags = ["News"]
