genesis_id = ""
system = "ZrCoin"
dependencies = ["Wave"]
icon = "zrcoin"

[token]
name = "zrcoin"
symbol = "ZRC"

[consensus]
consensus_type = ""
consensus_name = "Wave"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "The world's first commodity-backed blockchain option"

[crowdsales]
start_date = "2017-04-25T00:01:00"
end_date = "2017-05-24T12:59:00"
end_date_plan = "2017-05-24T12:59:00"
genesis_address = [""]
funding_terms = "https://zrcoin.io/blogitem/7"
funding_url = "https://zrcoin.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = 953
cap_limit = ["usd = 400000"]
raised = ["usd = 872430"]

[[links]]
type = "website"
name = "zrcoin.io"
url = "https://zrcoin.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "ZrCoin Whitepaper"
url = "https://zrcoin.io/files/Whitepaper_ENG.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "ZrCoin Blog"
url = "https://zrcoin.io/ablogs"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1832477.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/ZrCoin/media"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/zrcoin/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "ZrCoin Telegram"
url = "https://t.me/joinchat/AAAAAEDj28WzzuNh5j6tVg"
icon = "telegram.png"
tags = ["News"]
