
genesis_id = ""
system = "VinChain Token"
dependencies = ["Ethereum"]
icon = "vinchaintoken"

[token]
name = "vinchain token"
symbol = "VIN"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Whole truth about vehicle’s history on blockchain."

[crowdsales]
start_date = "2017-11-20T02:00:00"
end_date = "2017-11-26T03:00:00"
end_date_plan = "2017-11-26T03:00:00"
genesis_address = [""]
funding_terms = "https://vinchain.io"
funding_url = "https://vinchain.io"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = ["usd = 34500000"]
raised = [""]

[specs]
supply = 1000000000

[[links]]
type = "website"
name = "vinchain.io"
url = "https://vinchain.io"
tags = ["Main"]

[[links]]
type = "paper"
name = "VinChain Token Whitepaper"
url = "https://vinchain.io/files/white_paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "VinChain Token Github"
url = "https://github.com/VINChain"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = " Blog"
url = "https://medium.com/@VINChain"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/VINChain_io"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "VinChain Token Telegram"
url = "https://t.me/vinchainio"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/vinchainio/"
icon = "facebook.png"
tags = ["News"]
