genesis_id = ""
system = "Lordmancer II"
dependencies = ["Ethereum"]
icon = "lordmancerii"

[token]
name = "lordmancer token"
symbol = "LC"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Mobile MMORPG where players mine cryptocurrency"

[crowdsales]
start_date = "2017-08-21T06:00:00"
end_date = "2017-09-21T06:00:00"
end_date_plan = "2017-09-21T06:00:00"
genesis_address = [""]
funding_terms = "http://lordmancer2.io/terms_en"
funding_url = "http://lordmancer2.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "lordmancer2.io"
url = "http://lordmancer2.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Lordmancer II Whitepaper"
url = "https://drive.google.com/file/d/0ByRyBAt1-M4pdUl6LXE4cWlHWms/view"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Lordmancer II GitHub"
url = "https://github.com/lm2-ico/contracts"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2059852.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/LordmancerI"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Lordmancer II Telegram"
url = "https://t.me/lm2ico"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Lordmancer II Slack"
url = "https://lordmancerico.slack.com/join/shared_invite/MjIwNDE1NTI3ODA4LTE1MDE2NzY2NDEtNDYxYTA5NjIwNg"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Lordmancer2/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCR7woS5tfu9UBmJObOII5ow"
icon = "youtube.png"
tags = ["News"]
