genesis_id = ""
system = "Creativechain"
dependencies = ["independent"]
icon = "creativechain"

[token]
name = "creativechain token"
symbol = "CREA"

[consensus]
consensus_type = "PoW"
consensus_name = "Proof-of-Work"

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Multimedia Content Distribution"

[crowdsales]
start_date = "2017-03-15T00:00:00"
end_date = "2017-05-01T00:00:00"
end_date_plan = "2017-05-01T00:00:00"
genesis_address = ["3DxW7NDrpkyK3N71vtoKyVNGW8oYqnWuH2","1GJdGn4x47Y3ZMfSy3DPxiYT4zgta4Tez"]
funding_terms = "http://creativechain.org/ico/"
funding_url = "http://creativechain.org/ico/"
tokens_sold = 115000000
tokens_issued = 115000000
btc_raised = ""
cap_limit = ["usd = 7947316"]
raised = [""]

[[links]]
type = "website"
name = "creativechain.org"
url = "http://creativechain.org/project/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Creativechain Whitepaper"
url = "http://creativechain.org/wp-content/uploads/2017/03/Whitepaper-Creativechain-1.2.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Creativechain GitHub"
url = "https://github.com/creativechain"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1809920.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Creative_Chain"
icon = "twitter.png"
tags = ["News"]


[[links]]
type = "custom"
name = "Creativechain Telegram"
url = "https://telegram.me/creativechain"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Thecreativechain/?fref=ts"
icon = "facebook.png"
tags = ["News"]
