[crowdsales]
start_date = ""
end_date = ""
end_date_plan = ""
genesis_address = ["8VKbzETBUDXeGeEC2kujSKE2kojK1e6HEm"]
funding_terms = ""
funding_url = "https://bitconnectcoin.co/"
tokens_sold = 6380455
tokens_issued = 28000000
btc_raised = ""
cap_limit = [62699496]
raised = [""]
