
[crowdsales]
start_date = ""
end_date = ""
end_date_plan = ""
genesis_address = [""]
funding_terms = ""
funding_url = "http://blocknet.co/"
tokens_sold = 3910516
tokens_issued = 3910516
btc_raised = ""
cap_limit = [""]
raised = [""]
