[crowdsales]
start_date = ""
end_date = ""
end_date_plan = ""
genesis_address = [""]
funding_terms = ""
funding_url = "http://roundcoin.org/"
tokens_sold = 850000000
tokens_issued = 1000000000
btc_raised = ""
cap_limit = [""]
raised = [""]
