[crowdsales]
start_date = "2014-07-18T00:00:00"
end_date = "2014-08-18T00:00:00"
genesis_address = ["132aBrspLgL54cm9eQfGNFLGqXwBRQrugc"]
funding_terms = "http://storj.io/CrowdsaleTerms.pdf"
funding_url = "http://storj.io/crowdsale.html"
tokens_sold = 35039704.0
btc_raised = 910.0
