
[crowdsales]
start_date = ""
end_date = ""
end_date_plan = ""
genesis_address = [""]
funding_terms = ""
funding_url = "https://stratisplatform.com/"
tokens_sold = 98385148
tokens_issued = 98385148
btc_raised = ""
cap_limit = [""]
raised = [""]
