
[crowdsales]
start_date = ""
end_date = ""
end_date_plan = ""
genesis_address = [""]
funding_terms = ""
funding_url = "https://taas.fund/"
tokens_sold = ""
tokens_issued = ""
btc_raised = "6196.93"
cap_limit = [""]
raised = [""]
