
[crowdsales]
start_date = ""
end_date = ""
end_date_plan = ""
genesis_address = [""]
funding_terms = ""
funding_url = "http://www.veltor.org/"
tokens_sold = ""
tokens_issued = "554855.0"
btc_raised = ""
cap_limit = [""]
raised = [""]
