
[crowdsales]
start_date = ""
end_date = ""
end_date_plan = ""
genesis_address = [""]
funding_terms = ""
funding_url = "http://zclassic.org"
tokens_sold = 1349963
tokens_issued = 1349963
btc_raised = ""
cap_limit = [""]
raised = [""]
