genesis_id = ""
system = "Digital Developers Fund"
dependencies = ["Ethereum"]
icon = "digitaldevelopersfund"

[token]
name = "ddf token"
symbol = "DDF"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Investment fund focusing on digital assets"

[crowdsales]
start_date = "2017-07-10T00:00:00"
end_date = "2017-08-10T23:59:00"
end_date_plan = "2017-08-10T23:59:00"
genesis_address = [""]
funding_terms = "https://www.digitaldevelopersfund.com/terms-of-token-sale/"
funding_url = "https://www.digitaldevelopersfund.com/ico/"
tokens_sold = 6428932
tokens_issued = 250000000
btc_raised = ""
cap_limit = [""]
raised = ["usd = 2039193"]

[[links]]
type = "website"
name = "digitaldevelopersfund.com"
url = "https://www.digitaldevelopersfund.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Digital Developers Fund Whitepaper"
url = "https://www.digitaldevelopersfund.com/wp-content/uploads/2017/06/DDF.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Digital Developers Fund GitHub"
url = "https://github.com/digitaldevelopersfund/ddf"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1992157.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/DigitalDevFund"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Digital Developers Fund Telegram"
url = "https://t.me/DigitalDevelopersFund"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Digital Developers Fund Slack"
url = "https://digitaldevelopersfund.slack.com/signup"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/digitaldevelopersfund/"
icon = "facebook.png"
tags = ["News"]
