genesis_id = ""
system = "Belacoin"
icon = "belacoin"
dependencies = ["independent"]

[token]
name = "Belacoin"
symbol = "BELA"

[consensus]
type = "Proof-of-Work"
algorithm = ""

[aliases]
coinmarketcap = "BelaCoin"

[descriptions]
state = "Public"
system_type = "cryptocurrency"
headline = "Supercharging entrepreneurship with the power of the blockchain"
tags = [""]
page_state = ""

[specs]

[first_price]

[flags]

[[links]]
type = "website"
name = "belacoin.org"
url = "http://belacoin.org/"
icon = "site.png"
tags = ["Main"]

[[links]]
type = "github"
name = "Belacoin GitHub"
url = "https://github.com/theambiafund/belacoin"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "paper"
name = "Belacoin Whitepaper"
url = "http://belacoin.org/whitepaper.pdf"
icon = "whitepaper.png"
tags = ["Science"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1373100.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/belacoin"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Belacoin Slack"
url = "http://belacoin.herokuapp.com/"
icon = "slack.png"
tags = ["News"]
