genesis_id = ""
system = "Decentraland"
dependencies = ["Ethereum"]
icon = "decentraland"

[token]
name = "decentraland token"
symbol = "MANA"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "3D virtual world on blockchain"

[crowdsales]
start_date = "2017-08-18T00:00:00"
end_date = "2017-08-18T00:00:00"
end_date_plan = "2017-08-18T00:00:00"
genesis_address = [""]
funding_terms = "https://decentraland.org/"
funding_url = "https://decentraland.org/tokensale"
tokens_sold = 1122354557
tokens_issued = 2805886393
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "decentraland.org"
url = "https://decentraland.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Decentralandb Whitepaper"
url = "https://decentraland.org/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Decentraland GitHub"
url = "https://github.com/decentraland"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Decentraland Blog"
url = "https://blog.decentraland.org/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1968414.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/decentraland"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/decentraland/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/decentraland/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCLXcTgzr05cFZaN972nuEXw"
icon = "youtube.png"
tags = ["News"]
