genesis_id = ""
system = "Ubiq"
icon = "ubiq"
dependencies = ["Ethereum"]

[token]
name = "ubiq"
symbol = "UBQ"

[consensus]
type = "ERC20 Token"
algorithm = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Platform for the creation and implementation of smart contracts and decentralized applications"
tags = ["DAO"]
hashtag = "##ubiq"
page_state = "ready"

[aliases]
coinmarketcap = "Ubiq"

[specs]
total_tokens = 37342384.0

[[links]]
name = "ubiqsmart.com"
url = "https://ubiqsmart.com/"
type = "website"
icon = "website.png"
tags = ["Main"]

[[links]]
name = "Explorer"
url = "https://ubiqscan.io/en"
type = "explorer"
icon = "blockr.png"
tags = ["Main", "Apps", "Analytics"]

[[links]]
name = "Ubiq GitHub"
url = "https://github.com/ubiq"
type = "github"
icon = "github.png"
tags = ["Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1763606.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
name = "Twitter"
url = "https://twitter.com/ubiqsmart"
type = "twitter"
icon = "twitter.png"
tags = ["News"]

[[links]]
name = "Ubiq blog"
url = "https://medium.com/the-ubiq-report"
type = "blog"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "slack"
name = "Ubiq Slack"
url = "http://slack.ubiqsmart.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
name = "reddit"
url = "https://www.reddit.com/r/Ubiq/"
type = "reddit"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCaKJfiYPY-gWC5932p23kyw/videos"
icon = "youtube.png"
tags = ["News"]

[[links]]
name = "Markets CMC"
url = "https://coinmarketcap.com/currencies/ubiq/#markets"
type = "custom"
icon = "link.png"
tags = ["Apps", "Analytics"]

[[links]]
name = "Bittrex"
url = "https://bittrex.com"
type = "custom"
icon = "bittrex.png"
tags = ["Apps", "Exchange"]

[flags]
quantum = true
