genesis_id = ""
system = "Numeraire"
icon = "numeraire"
dependencies = ["Ethereum"]

[token]
name = "numeraire"
symbol = "NMR"

[consensus]
type = "ERC20 Token"
algorithm = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Hedge fund built by a network of data scientists."
tags = ["DAO"]
hashtag = "#Numeraire"
page_state = "ready"

[aliases]
coinmarketcap = "Numeraire"

[specs]
total_tokens = 2223451.0

[[links]]
name = "numer.ai"
url = "https://numer.ai/"
type = "website"
icon = "website.png"
tags = ["Main"]

[[links]]
name = "Whitepaper"
url = "https://numer.ai/whitepaper.pdf"
type = "paper"
icon = "paper.png"
tags = ["Main", "Science"]

[[links]]
name = "Explorer"
url = "https://etherscan.io/token/0x1776e1F26f98b1A5dF9cD347953a26dd3Cb46671"
type = "explorer"
icon = "blockr.png"
tags = ["Main", "Apps", "Analytics"]

[[links]]
name = "Numeraire GitHub"
url = "https://github.com/numerai"
type = "github"
icon = "github.png"
tags = ["Code"]

[[links]]
name = "Twitter"
url = "https://twitter.com/numerai"
type = "twitter"
icon = "twitter.png"
tags = ["News"]

[[links]]
name = "Forum"
url = "https://forum.numer.ai/"
type = "forum"
icon = "forum.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Numeraire Slack"
url = "https://slack.numer.ai/"
icon = "slack.png"
tags = ["News"]

[[links]]
name = "reddit"
url = "https://www.reddit.com/r/CryptoCurrency/search?q=Numeraire"
type = "reddit"
icon = "reddit.png"
tags = ["News"]

[[links]]
name = "Markets CMC"
url = "https://coinmarketcap.com/assets/numeraire/#markets"
type = "custom"
icon = "link.png"
tags = ["Apps", "Analytics"]

[[links]]
name = "Cryptsy"

url = "https://www.cryptsy.com/users/register?refid=243274"
type = "custom"
icon = "cryptsy.png"
tags = ["Apps", "Exchange"]

[[links]]
name = "Bittrex"
url = "https://bittrex.com"
type = "custom"
icon = "bittrex.png"
tags = ["Apps", "Exchange"]

[flags]
quantum = true
