genesis_id = ""
system = "Crypviser"
dependencies = ["independent"]
icon = "crypviser"

[token]
name = "cv coin"
symbol = "CVCOIN"

[consensus]
type = ""
algorithm = ""

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Encrypted communication App on Blockchain with it`s own cryprocurrency"
tags = ["DAO"]
page_state = "ready"

[aliases]
coinmarketcap = "CVCoin"
nickname = "CVCoin"

[[links]]
type = "website"
name = "crypviser.net"
url = "https://ico.crypviser.net/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Crypviser Whitepaper"
url = "https://ico.crypviser.net/docs/CrypViser_Whitepaper_v.1.2.pdf"
tags = ["Main", "Science"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1922625.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/cvcoin_ico"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Crypviser Telegram"
url = "https://t.me/crypviser"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Crypviser Slack"
url = "https://crypviser.slack.com/join/shared_invite/MjE5MjMzMTMyNzU3LTE1MDEyNTEyNTktNGE4NjI1MDUzYg"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/cvcico/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCw4jiLq9vHfajMyQQQ1ixBA"
icon = "youtube.png"
tags = ["News"]
