genesis_id = ""
system = "Make It Viral"
dependencies = ["independent"]
icon = "makeitviral"

[token]
name = "make it viral token"
symbol = "MIV"

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Video Sharing Platform"

[crowdsales]
start_date = "2017-07-18T16:00:00"
end_date = "2017-10-31T23:59:00"
end_date_plan = "2017-10-31T23:59:00"
genesis_address = [""]
funding_terms = "https://www.miv.life/miv_terms.pdf"
funding_url = "https://www.miv.life/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "miv.life"
url = "http://miv.life/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Make It Viral Whitepaper"
url = "http://188.226.133.21/MakeItViral_WhitePaper_May_2017.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Make It Viral GitHub"
url = "https://github.com/medsi2/MIV"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Make It Viral Blog"
url = "https://medium.com/@MIVlife"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1983414.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/MIVlife"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Make It Viral Telegram"
url = "https://t.me/joinchat/AAAAAEQT69BSXVezrhhoCw"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Make It Viral Slack"
url = "https://makeitviral.slack.com/join/shared_invite/MTg1OTExNjM1Njk5LTE0OTUzMDUyNzAtNThlNTA4N2ViZg"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/MIVlife/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/MIVlife/"
icon = "facebook.png"
tags = ["News"]
