genesis_id = ""
system = "Dimcoin"
dependencies = ["NEM Mosaic"]
icon = "dimcoin"

[token]
name = "dimcoin token"
symbol = "DIM"

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Network of Intrinsically Tradeable Smart Tokens"

[crowdsales]
start_date = "2017-07-01T00:00:00"
end_date = "2017-09-27T00:00:00"
end_date_plan = "2017-09-27T00:00:00"
genesis_address = [""]
funding_terms = "https://www.dimcoin.io/"
funding_url = "https://www.dimcoin.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 9000000000

[[links]]
type = "website"
name = "dimcoin.io"
url = "https://www.dimcoin.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Dimcoin Whitepaper"
url = "https://www.dimcoin.io/DIMCOIN-whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1986414.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/DIMCOIN_ICO"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Dimcoin Telegram"
url = "https://t.me/dimcoin"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/DIMCOINICO/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCT0Sq4kPSYK7oFNbXPiyDng"
icon = "youtube.png"
tags = ["News"]
