genesis_id = ""
system = "Pillar"
dependencies = ["Ethereum"]
icon = "pillar"

[token]
name = "pillar token"
symbol = "PLR"

[consensus]
type = "ERC20 Token"
algorithm = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Next generation, open-source wallet"
tags = ["DAO"]
page_state = "ready"

[aliases]
coinmarketcap = "Pillar"
nickname = "Pillar"

[[links]]
type = "website"
name = "pillarproject.io"
url = "https://pillarproject.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Pillar Whitepaper"
url = "https://pillarproject.io/wp-content/uploads/2017/07/PillarProjectGrayPaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Pillar GitHub"
url = "https://github.com/twentythirty/PillarToken"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Pillar Blog"
url = "https://medium.com/@pullnews"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2048187"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/PillarWallet"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Pillar Telegram"
url = "https://t.me/pillarproject"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/PillarProject/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/twentythirty2030/"
icon = "facebook.png"

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/c/PillarProject"
icon = "youtube.png"
tags = ["News"]
