genesis_id = ""
system = "Presearch"
dependencies = ["Ethereum"]
icon = "presearch"

[token]
name = "presearch token"
symbol = "PSTs"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized search engine, powered by community"

[crowdsales]
start_date = "2017-07-25T14:00:00"
end_date = "2017-08-25T14:00:00"
end_date_plan = "2017-08-25T14:00:00"
genesis_address = [""]
funding_terms = "http://www.presearch.io"
funding_url = "http://www.presearch.io"
tokens_sold = ""
tokens_issued = 1000000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "presearch.io"
url = "http://www.presearch.io"
tags = ["Main"]

[[links]]
type = "paper"
name = "Presearch Whitepaper"
url = "https://www.presearch.io/uploads/WhitePaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/decentralsearch"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Presearch Telegram"
url = "https://t.me/presearch"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Presearch Slack"
url = "https://presearch.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/presearch.io/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCgU-2uscwUP6x27mUpCGWwg"
icon = "youtube.png"
tags = ["News"]
