genesis_id = ""
system = "TaaS"
dependencies = ["Ethereum"]
icon = "taas"

[token]
name = "taase"
symbol = "TAAS"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Closed-End Investment Fund"

[aliases]
coinmarketcap = "TaaS"

[specs]
supply = ""

[flags]

[[links]]
type = "website"
name = "taas.fund"
url = "https://taas.fund/"
tags = ["Main"]

[[links]]
type = "paper"
name = "TaaS Whitepaper"
url = "http://taas.fund/media/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "TaaS GitHub"
url = "https://github.com/reddit/reddit"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "TaaS Blog"
url = "https://medium.com/@TaaS"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1792938.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/taasfundk"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "TaaS Slack"
url = "https://taasfund.signup.team/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = ""
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCzhLXQA9h7RQKlPWViKIzNw"
icon = "youtube.png"
tags = ["News"]

[[links]]
type = "custom"
name = "TaaS Telegram"
url = "https://t.me/taasfundS"
icon = "telegram.png"
tags = ["News"]
