genesis_id = ""
system = "Stratis"
dependencies = ["independent"]
icon = "stratis"

[token]
name = "stratise"
symbol = "STRAT"

[consensus]
consensus_type = "proof-of-stake"
consensus_name = "POS"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Flexible Blockchain Development Platform"

[aliases]
coinmarketcap = "Stratis"

[specs]
supply = ""

[flags]

[[links]]
type = "website"
name = "stratisplatform.com"
url = "https://stratisplatform.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Stratis Whitepaper"
url = "https://stratisplatform.com//files/Stratis_Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Stratis GitHub"
url = "https://github.com/stratisproject"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Stratis Blog"
url = "https://stratisplatform.com/blog/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1512202.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/stratisplatform"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Stratis Slack"
url = "https://stratis-invite.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/stratisplatform/"
icon = "reddit.png"
tags = ["News"]
