genesis_id = ""
system = "Stox"
dependencies = ["Ethereum"]
icon = "stox"

[token]
name = "stox token"
symbol = "STX"

[consensus]
type = "ERC20 Token"
algorithm = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Blockchain Prediction Market"
tags = ["DAO"]
page_state = "ready"

[aliases]
coinmarketcap = "Stox"
nickname = "Stox"

[[links]]
type = "website"
name = "stox.com"
url = "https://www.stox.com/en/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Stox Whitepaper"
url = "https://www.stox.com/assets/stox-whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Stox GitHub"
url = "https://github.com/stx-technologies/stox-token"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Stox Blog"
url = "https://steemit.com/@stx"
icon = "steem.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2035348.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/stx_coin"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Stox Telegram"
url = "https://t.me/joinchat/DByWw0Pnq9BAy4FqPv_Lyg"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/STOX/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UC_hd4EfAzXr5NFfOTw7nXjA"
icon = "youtube.png"
tags = ["News"]
