genesis_id = ""
system = "SLOGN"
dependencies = ["Ethereum"]
icon = "slogn"

[token]
name = "slogn coin"
symbol = "SLOGN"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Logistics Platform Powered by Blockchain & AI"

[crowdsales]
start_date = "2017-07-25T15:00:00"
end_date = "2017-08-15T02:59:59"
end_date_plan = "2017-08-15T02:59:59"
genesis_address = [""]
funding_terms = "https://www.slogn.net/ico"
funding_url = "https://www.slogn.net/ico"
tokens_sold = 5600000000
tokens_issued = 8000000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "slogn.net"
url = "https://www.slogn.net/"
tags = ["Main"]

[[links]]
type = "paper"
name = "SLOGN Whitepaper"
url = "https://github.com/SLOGNNet/whitepaper/blob/master/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "SLOGN GitHub"
url = "https://github.com/SLOGNNet"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "SLOGN Blog"
url = "https://medium.com/@SLOGN"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2005737"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/slogncoin"
icon = "twitter.png"
tags = ["News"]
