genesis_id = ""
system = "EncryptoTel"
dependencies = ["Waves"]
icon = "encryptotel"

[token]
name = "encryptotel coin"
symbol = "ETT"

[consensus]
consensus_type = ""
consensus_name = "Waves"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "The First Secure Cloud Private Branch eXchange"

[crowdsales]
start_date = "2017-04-24T00:01:00"
end_date = "2017-05-31T00:00:00"
end_date_plan = "2017-05-31T00:00:00"
genesis_address = [""]
funding_terms = "https://encryptotel.com/"
funding_url = "http://ico.encryptotel.com/"
tokens_sold = ""
tokens_issued = 100000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "encryptotel.com"
url = "https://encryptotel.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "EncryptoTel Whitepaper"
url = "http://ico.encryptotel.com/assets/pdf/EncryptoTel_WP_v1.pdf"
tags = ["Main", "Science"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1848180.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/encryptotel"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/encryptotel"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "slack"
name = "EncryptoTel Slack"
url = "https://encryptotel.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UC8jbjwlygSJGNCjPpRrHwqw"
icon = "youtube.png"
tags = ["News"]
