genesis_id = ""
system = "Spectiv"
dependencies = ["Ethereum"]
icon = "spectiv"

[token]
name = "spectiv token"
symbol = "Specs"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Dedicated Virtual Reality Streaming Platform"

[crowdsales]
start_date = "2017-08-14T12:00:00"
end_date = "2017-09-04T23:59:00"
end_date_plan = "2017-09-04T23:59:00"
genesis_address = [""]
funding_terms = "https://www.spectivvr.com/"
funding_url = "https://www.spectivvr.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = ["usd = 40000000"]
raised = [""]

[[links]]
type = "website"
name = "spectivvr.com"
url = "https://www.spectivvr.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Spectiv Whitepaper"
url = "https://drive.google.com/file/d/0B2_BLkYG_TdGRGE2MGpyWE1oWkk/viewn"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Spectiv Blog"
url = "https://medium.com/spectiv-vr"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1975254.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/spectivvr"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Spectiv Slack"
url = "https://slackpass.io/spectivvr"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/spectivvr/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCPrxpI__VFaV0PUh5W_FMug"
icon = "youtube.png"
tags = ["News"]
