genesis_id = ""
system = "8 Сurcuit Studios"
dependencies = ["Ethereum"]
icon = "8curcuitstudios"

[token]
name = "8bit token"
symbol = "8BT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Blockchain Based Video Game Develoment"

[crowdsales]
start_date = "2017-07-17T07:17:00"
end_date = "2017-08-18T08:18:00"
end_date_plan = "2017-08-18T08:18:00"
genesis_address = [""]
funding_terms = "https://8circuitstudios.com/"
funding_url = "https://8circuitstudios.com/"
tokens_sold = 33000000
tokens_issued = 100000000
btc_raised = ""
cap_limit = ["usd = 33000000"]
raised = [""]

[[links]]
type = "website"
name = "8circuitstudios.com"
url = "https://8circuitstudios.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "8 Сurcuit Studios Whitepaper"
url = "https://github.com/8CircuitStudios/8BitToken/blob/master/Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "8 Сurcuit Studios GitHub"
url = "https://github.com/8CircuitStudios/8BitToken"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/@8circuitstudios"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/8circuitstudios/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCNPgn6Z54YGXExvSWUeDDHg"
icon = "youtube.png"
tags = ["News"]
