genesis_id = ""
system = "Prospectors"
dependencies = ["Ethereum"]
icon = "prospectors"

[token]
name = "gold token"
symbol = "GOLD"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Massive Multiplayer Online Real Time Economic Strategy"

[crowdsales]
start_date = "2017-06-12T10:00:00"
end_date = "2017-06-25T14:00:00"
end_date_plan = "2017-06-25T14:00:00"
genesis_address = [""]
funding_terms = "https://prospectors.io/"
funding_url = "https://prospectors.io/"
tokens_sold = ""
tokens_issued = 220000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "prospectors.io"
url = "https://prospectors.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Prospectors Whitepaper"
url = "https://drive.google.com/file/d/0B0quEKxjhqglbzlZa041WXp3TVU/view"
tags = ["Main", "Science"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1877080.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Prospectors Slack"
url = "http://prospectors.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/prospectors.io/"
icon = "facebook.png"
tags = ["News"]
