genesis_id = ""
system = "Tezos"
dependencies = "independent"
icon = "tezos"

[token]
name = "tezos token"
symbol = "TXZ"

[consensus]
consensus_type = "proof-of-stake"
consensus_name = "POS"

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Self-amending Crypto-ledger"

[crowdsales]
start_date = "2017-07-01T00:00:00"
end_date = "2017-07-13T00:00:00"
end_date_plan = "2017-07-13T00:00:00"
genesis_address = [""]
funding_terms = "https://tezos.ch/pages/static/Tezos%20Contribution%20Terms.pdf?utm_source=Tezos&utm_campaign=682d936488-EMAIL_CAMPAIGN_2017_07_01&utm_medium=email&utm_term=0_d8f4b4112e-682d936488-117506397"
funding_url = "https://www.tezos.com/"
tokens_sold = ""
tokens_issued = 10000000000
btc_raised = 97268
cap_limit = [""]
raised = ["usd = 230595616"]

[[links]]
type = "website"
name = "tezos.com"
url = "https://www.tezos.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Tezos Whitepaper"
url = "https://www.tezos.com/static/papers/white_paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Tezos GitHub"
url = "https://github.com/tezos/tezos"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Tezos Blog"
url = "https://medium.com/tezos"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=715818.0"
icon = "bitcoin.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/tez0s"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Tezos Slack"
url = "http://slack.tezos.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/tezosledger/"
icon = "facebook.png"
tags = ["News"]
