genesis_id = ""
system = "Tezos"
dependencies = "independent"
icon = "tezos"

[token]
name = "tezos"
symbol = "TEZOS"

[consensus]
consensus_type = "proof-of-stake"
consensus_name = "Tezos"

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Distributed consensus platform with meta-consensus capability"

[aliases]
coinmarketcap = ""

[crowdsales]
start_date = "2017-05-22T06:00:00"
end_date = "2017-06-22T00:10:00"
end_date_plan = "2017-06-22T00:00:00"
genesis_address = [""]
funding_terms = ""
funding_url = "https://www.tezos.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = ""

[flags]

[[links]]
type = "website"
name = "tezos.com"
url = "https://www.tezos.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Tezos Whitepaper"
url = "https://tezos.com/pdf/white_paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Tezos GitHub"
url = "https://github.com/tezos/tezos"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Tezos Blog"
url = "https://tezos.com/blog/index.html"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=715818.0"
icon = "bitcoin.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/tez0s"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Tezos Slack"
url = "http://slack.tezos.com/"
icon = "slack.png"
tags = ["News"]
