genesis_id = ""
system = "Nimfamoney"
dependencies = ["Ethereum"]
icon = "nimfamoney"

[token]
name = "nimfamoney token"
symbol = "NIMFA"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "The world’s first decentralized cryptocurrency lending platform"

[crowdsales]
start_date = "2017-08-29T10:00:00"
end_date = "2017-08-31T12:01:00"
end_date_plan = "2017-08-31T12:01:00"
genesis_address = [""]
funding_terms = "http://www.nimfamoney.io/terms.pdf"
funding_url = "http://www.nimfamoney.io/"
tokens_sold = ""
tokens_issued = 100000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "nimfamoney.io"
url = "http://www.nimfamoney.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Nimfamoney Whitepaper"
url = "http://www.nimfamoney.io/ENG_V.1.0_Whitepaper_ICO_Nimfamoney.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Nimfamoney GitHub"
url = "https://github.com/nimfamoney"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2040087"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/nimfamoney"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Nimfamoney Telegram"
url = "https://t.me/Nimfamoney"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Nimfamoney Slack"
url = "http://nimfamoney.io/slack"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/nimfamoney/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCVcz2eKXt8Ih6T3RVRvq6sQ"
icon = "youtube.png"
tags = ["News"]
