genesis_id = ""
system = "Silent Notary"
dependencies = ["Ethereum"]
icon = "silentnotary"

[token]
name = "silent notary token"
symbol = "SNTR"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Blockchain service based on confirming the existence of events"

[crowdsales]
start_date = "2017-08-21T00:00:00"
end_date = "2017-09-04T00:00:00"
end_date_plan = "2017-09-04T00:00:00"
genesis_address = [""]
funding_terms = "https://silentnotary.com/"
funding_url = "https://silentnotary.com/"
tokens_sold = ""
tokens_issued = 1000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "silentnotary.com"
url = "https://silentnotary.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Silent Notary Whitepaper"
url = "https://drive.google.com/file/d/0By2meS6G5zw5Wnhvcnh0TmhRR0U/view"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Silent Notary GitHub"
url = "https://github.com/SilentNotary/ICO-SN"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/SilentNotary"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2016357.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Silent Notary Slack"
url = "https://silentnotary.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Silent Notary Telegram"
url = "https://t.me/icosilentnotary"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/SilentNotary"
icon = "facebook.png"
tags = ["News"]
