genesis_id = ""
system = "Crowdholding"
dependencies = ["Ethereum"]
icon = "crowdholding"

[token]
name = "crowdholding token"
symbol = "YUPIE"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Network of Intrinsically Tradeable Smart Tokens"

[crowdsales]
start_date = "2017-06-12T10:00:00"
end_date = "2017-06-25T14:00:00"
end_date_plan = "2017-06-25T14:00:00"
genesis_address = ["0x0F33bb20a282A7649C7B3AFf644F084a9348e933"]
funding_terms = "https://ico.crowdholding.com/"
funding_url = "https://ico.crowdholding.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 631000000

[[links]]
type = "website"
name = "ico.crowdholding"
url = "https://ico.crowdholding.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Crowdholding Whitepaper"
url = "https://docs.google.com/document/d/1RcOqAqnW89d8u8uS5E9W0gCz5k678SJFeWaRcxYkgdw/edit#heading=h.gd975316ob3y"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Crowdholding GitHub"
url = "https://github.com/crowdholdingico/YupieSmartContract"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Crowdholding Blog"
url = "https://medium.com/@crowdholding"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2082561.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/crowdholding"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Crowdholding Telegram"
url = "https://t.me/Crowdholding"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Crowdholding Slack"
url = "https://join.slack.com/t/crowdholdingico/shared_invite/MjIzMzg3NzU5OTkxLTE1MDE4NTUwMjctYTIwYzZlOTU2Yw"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Crowdholding/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Crowdholding/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCDmQRTVwVPBwLErsbXPyrRA"
icon = "youtube.png"
tags = ["News"]
