genesis_id = "000000ecd77baa224eebc9960e5a1632ad07858be83ae9b96d1e6fea4d675a68"
system = "IOCoin"
icon = "iocoin"
dependencies = ["independent"]

[aliases]
coinmarketcap = "I/O Coin"

[ratings]
rating_cyber = 1.0

[descriptions]
state = "Public"
system_type = "cryptocurrency"

[consensus]
type = "PoS"
algorithm = "X11"

[token]
name = "IOCoin"
symbol = "IOC"

[[links]]
type = "website"
name = "iocoin.io"
url = "http://iocoin.io/"
icon = "website.png"
tags = ["Main"]

[[links]]
type = "paper"
name = "I/O Coin Whitepaper"
url = "http://iodigital.io/wp-content/uploads/2016/06/whitepaper_dions.pdf"
tags = ["Main", "Science"]

[[links]]
type = "explorer"
name = "cryptoID Explorer"
url = "http://chainz.cryptoid.info/ioc/"
icon = "cryptoid.png"
tags = ["Main","Apps","Explorer","Analytics"]

[[links]]
type = "github"
name = "IOCoin GitHub"
url = "https://github.com/IOCoin/iocoin"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "forum"
name = "BTT Thread"
url = "https://bitcointalk.org/index.php?topic=695855.0"
icon = "forum.png"
tags = ["Main","News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=695855"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=695855"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/IO_Coin"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "I/O Coin Telegram"
url = "https://t.me/joinchat/CqVqS0O3PjCTx9bfp4CwOQ"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "I/O Coin Slack"
url = "https://iocoin.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/IODigitalCurrency/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/iodigitalblockchain/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCJ5GyhoieEi18FF9oIOuQKQ"
icon = "youtube.png"
tags = ["News"]

[first_price]
btc = 0.00000479
usd = 0.00176825
date = "2014-08-02T00:00:00"
