genesis_id = ""
system = "Poet"
dependencies = ["Ethereum"]
icon = "poet"

[token]
name = "poet token"
symbol = "POE"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Universal ledger for digital creative asset ownership"

[crowdsales]
start_date = "2017-08-08T12:00:00"
end_date = "2017-09-05T12:00:00"
end_date_plan = "2017-09-05T12:00:00"
genesis_address = [""]
funding_terms = "https://www.dropbox.com/s/prp147uqywcl10r/Poet_Token_Info.pdf?dl=0"
funding_url = "https://po.et/token"
tokens_sold = ""
tokens_issued = 3141592653
btc_raised = ""
cap_limit = ["usd = 10000000"]
raised = [""]

[[links]]
type = "website"
name = "po.et"
url = "https://po.et/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Poet Whitepaper"
url = "https://po.et/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Poet GitHub"
url = "https://github.com/poetapp"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1789222.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/_poetproject"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Poet Telegram"
url = "https://t.me/joinchat/GKMQ1kOQSdXVZpN1Rygcdw"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Poet Slack"
url = "https://poet-slack.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/poetproject/"
icon = "reddit.png"
tags = ["News"]
