genesis_id = ""
system = "OpenAnx"
dependencies = ["Ethereum"]
icon = "openanx"

[token]
name = "openanx token"
symbol = "OAX"

[consensus]
type = "ERC20 Token"
algorithm = "Ethereum"

[aliases]
coinmarketcap = "OpenAnx"
nickname = "OpenAnx"

[descriptions]
state = "Public"
system_type = "cryptocurrency"
headline = "Real world application of Decentralized Exchange"
tags = ["DAO"]
page_state = "ready"

[[links]]
type = "website"
name = "openanx.org"
url = "https://www.openanx.org/en/"
tags = ["Main"]

[[links]]
type = "paper"
name = "OpenAnx Whitepaper"
url = "https://www.openanx.org/en/assets/whitepaper/openANX_White_Paper_ENU.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "OpenAnx Blog"
url = "https://medium.com/@OAX_Foundation"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1943946"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/OAX_Foundation"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "OpenAnx Slack"
url = "https://openanx.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "OpenAnx Telegram"
url = "https://t.me/openanxteam"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/OpenANX/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCWzKmt7vtbjSprobArNzqBw"
icon = "youtube.png"
tags = ["News"]
