genesis_id = ""
system = "adToken"
dependencies = ["Ethereum"]
icon = "adtoken"

[token]
name = "adtoken token"
symbol = "ADT"

[consensus]
type = "ERC20 Token"
algorithm = "Ethereum"

[aliases]
coinmarketcap = "adToken"
nickname = "adToken"

[descriptions]
state = "Public"
system_type = "cryptocurrency"
headline = "Solution for digital advertising"
tags = ["DAO"]
page_state = "ready"

[[links]]
type = "website"
name = "adtoken.com"
url = "https://adtoken.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "adToken Whitepaper"
url = "https://adchain-white-paper.docsend.com/view/qnce6gy"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "adToken GitHub"
url = "https://github.com/adchain"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "adToken Blog"
url = "https://medium.com/@AdChain"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/ad_chain"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "adToken Slack"
url = "http://slack.adchain.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/adChain/"
icon = "reddit.png"
tags = ["News"]
