genesis_id = ""
system = "Enjin Coin"
dependencies = ["Ethereum"]
icon = "enjincoin"

[token]
name = "enjin coin"
symbol = "ENJ"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Smart cryptocurrency for gaming"

[crowdsales]
start_date = "2017-08-15T12:00:00"
end_date = "2017-09-15T12:00:00"
end_date_plan = "2017-09-15T12:00:00"
genesis_address = [""]
funding_terms = "https://enjincoin.io/"
funding_url = "https://enjincoin.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "enjincoin.io"
url = "https://enjincoin.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Enjin Whitepaper"
url = "https://enjincoin.io/enjincoin_whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Enjin Blog"
url = "https://medium.com/@coinfork"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/enjincs"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Enjin Slack"
url = "https://enjincoin.io/slack/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/EnjinCoin/"
icon = "reddit.png"
tags = ["News"]
