genesis_id = ""
system = "MyBit"
dependencies = ["Ethereum"]
icon = "mybit"

[token]
name = "mybit token"
symbol = "MYB"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Tokenizing Smart Enegry, AI, and Ownership"

[crowdsales]
start_date = "2017-07-17T12:00:00"
end_date = "2017-08-06T12:00:00"
end_date_plan = "2017-08-06T12:00:00"
genesis_address = [""]
funding_terms = "https://mybit.io/tokensale"
funding_url = "https://mybit.io/tokensale"
tokens_sold = ""
tokens_issued = 5000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "mybit.io"
url = "https://mybit.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "MyBit Whitepaper"
url = "http://www.mybit.io/docs/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Mybit GitHub"
url = "https://github.com/MyBitDev"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "MyBit Blog"
url = "https://medium.com/@MyBit_Blog"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1797720.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/MyBit_DApp"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Mybit Telegram"
url = "http://t.me/mybitio"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "MyBit Slack"
url = "https://mybit-dapp.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/user/MyBit_DApp/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/MyBitDApp/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCtLn7Vi-3VbsY5F9uF1RJYg"
icon = "youtube.png"
tags = ["News"]
