genesis_id = ""
system = "BitConnect"
dependencies = ["independent"]
icon = "bitconnect"

[token]
name = "bitconnect coin"
symbol = "BCC"

[consensus]
consensus_type = "peer-to-peer"
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "BitConnect coin is an open source, peer-to-peer, community driven decentralized cryptocurrency"

[aliases]
coinmarketcap = "BitConnect"

[specs]
supply = ""

[flags]

[[links]]
type = "website"
name = "bitconnectcoin.co"
url = "https://bitconnectcoin.co/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Whitepaper"
url = ""
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "BitConnection GitHub"
url = "https://github.com/bitconnectcoin/bitconnectcoin/blob/master/README.md"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Blog"
url = ""
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1681719.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/bitconnect"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Slack"
url = ""
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = ""
icon = "reddit.png"
tags = ["News"]


[[links]]
type = "custom"
name = "YouTube"
url = ""
icon = "youtube.png"
tags = ["News"]
