genesis_id = ""
system = "Rex"
dependencies = "Ethereum"
icon = "rex"

[token]
name = "rex token"
symbol = "REX"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized Multiple Listing Service"

[crowdsales]
start_date = "2017-07-31T00:00:00"
end_date = "2017-08-31T00:10:00"
end_date_plan = "2017-08-31T00:00:00"
genesis_address = [""]
funding_terms = "http://rexmls.com/tokensale.html"
funding_url = "http://rexmls.com/tokensale.html"
tokens_sold = ""
tokens_issued = 250000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "rexmls.com"
url = "http://rexmls.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Rex Whitepaper"
url = "https://github.com/rexmls/whitepaper/blob/master/readme.md"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Rex GitHub"
url = "https://github.com/rexmls"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Rex Blog"
url = "https://blog.rexmls.com/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/rexmls"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Rex Slack"
url = "https://rexmls.herokuapp.com/"
icon = "slack.png"
tags = ["News"]
