genesis_id = ""
system = "Blocknet"
dependencies = ["independent"]
icon = "blocknet"

[token]
name = "blocknet token"
symbol = "BLOCK"

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentrilized Application Platform"

[specs]
supply = ""

[flags]

[[links]]
type = "website"
name = "blocknet.co"
url = "http://blocknet.co/"
tags = ["Main"]

[[links]]
type = "github"
name = "Blocknet GitHub"
url = "https://github.com/atcsecure/blocknet"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Bancor Blog"
url = "http://blocknet.co/?page_id=138"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=829576.2195;wap2"
icon = "bitcointalk.png"
tags = ["Main","News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/The_Blocknet"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Blocknet Slack"
url = "https://blocknet.herokuapp.com/"
icon = "slack.png"
tags = ["News"]
