genesis_id = ""
system = "Pylon Network"
dependencies = ["Ethereum"]
icon = "pylonnetwork"

[token]
name = "pylon token"
symbol = "PYLON"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Renewable energy exchange platform"

[crowdsales]
start_date = "2017-09-04T00:00:00"
end_date = "2017-10-02T23:59:00"
end_date_plan = "2017-10-02T23:59:00"
genesis_address = [""]
funding_terms = "http://pylon-network.org/"
funding_url = "http://pylon-network.org/#ico"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "pylon-network.org"
url = "http://pylon-network.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Pylon Network Whitepaper"
url = "http://pylon-network.org/wp-content/uploads/2017/07/170730_WP-PYLON_EN.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Pylon Network Blog"
url = "http://pylon-network.org/blog"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2054297"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/KlenergyTech"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Pylon Network Telegram"
url = "https://t.me/pylonnetworkofficialtelegram"
icon = "telegram.png"
tags = ["News"]
