genesis_id = ""
system = "BOScoin"
dependencies = ["independent"]
icon = "boscoin"

[token]
name = "BOScoin token"
symbol = "BOS"

[consensus]
consensus_type = "PoW"
consensus_name = "Proof-of-Work"

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Congressional Network for Trust Contracts"

[aliases]
coinmarketcap = "Bancor"

[crowdsales]
start_date = "2017-05-10T00:00:00"
end_date = "2017-06-20T00:00:00"
end_date_plan = "2017-06-20T00:00:00"
genesis_address = [""]
funding_terms = "http://boscoin.wpengine.com/?page_id=114"
funding_url = "https://boscoin.io/member/join/?lang=en"
tokens_sold = ""
tokens_issued = 276093688.786
btc_raised = 6902.342
cap_limit = [""]
raised = ["usd = 12202995.54"]

[[links]]
type = "website"
name = "boscoin.io"
url = "https://www.boscoin.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "BOScoin Whitepaper"
url = "https://www.boscoin.io/wordpress/wp-content/themes/boscoin/src/pdf/boscoinwhitepaperv20170202.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "BOScoin GitHub"
url = "https://github.com/owlchain/owlchain-core"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "BOScoin Blog"
url = "https://medium.com/boscoin"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1759662.msg17571483#msg175714830"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/boscoinio"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "BOScoin Slack"
url = "https://slack-boscoin.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/boscoin/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/boscoinio"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCRjoA41Ukj_Vnt9Ec6oi7Qw"
icon = "youtube.png"
tags = ["News"]
