genesis_id = ""
system = "FundYourselfNow"
dependencies = ["Ethereum"]
icon = "fundyourselfnow"

[token]
name = "fundyourselfnow coin"
symbol = "FYN"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Revolutionizing Crowdfunding via Blockchain"

[crowdsales]
start_date = "2017-06-13T14:00:00"
end_date = "2017-06-31T17:00:00"
end_date_plan = "2017-06-31T17:00:00"
genesis_address = [""]
funding_terms = "https://www.fundyourselfnow.com/"
funding_url = "https://www.fundyourselfnow.com/"
tokens_sold = ""
tokens_issued = 12500000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "fundyourselfnow.com"
url = "https://www.fundyourselfnow.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "FundYourselfNow Whitepaper"
url = "http://www.fundyourselfnow.com/wp-content/uploads/2017/03/FYN_Business_Outline.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "FundYourselfNow GitHub"
url = "https://github.com/PinnacleOne/FYNTokens"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "FundYourselfNow Blog"
url = "https://medium.com/@FundYourselfNow/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1901678.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/fundyourselfnow"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "FundYourselfNow Telegram"
url = "https://telegram.me/fundyourselfnow"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "FundYourselfNow Slack"
url = "https://fundyourselfnow.slack.com/join/shared_invite/MTk2MTQ1MjU4MjkyLTE0OTcyNDUzNTYtZDhhM2I1NzQ1ZQ"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/fundyourselfnow/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCv_GbaPjt44RhiKMEEywNYQ"
icon = "youtube.png"
tags = ["News"]
