genesis_id = ""
system = "Slot N Slot"
dependencies = ["Ethereum"]
icon = "slotnslot"

[token]
name = "slot token"
symbol = "SLOT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Superfast Ethereum Slot Platform on mobile&web"

[crowdsales]
start_date = "2017-08-20T08:00:00"
end_date = "2017-09-03T08:00:00"
end_date_plan = "2017-09-03T08:00:00"
genesis_address = [""]
funding_terms = "https://slotnslot.com"
funding_url = "https://slotnslot.com"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "slotnslot.com"
url = "https://slotnslot.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Slot N Slot Whitepaper"
url = "https://github.com/SlotNSlot/whitepaper/blob/master/whitepaper.md#head19"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Slot N Slot GitHub"
url = "https://github.com/SlotNSlot/SlotNSlot"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Slot N Slot Blog"
url = "https://medium.com/@kkenji1024"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/slotnslot"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Slot N Slot Telegram"
url = "https://t.me/slotnslot_ico"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/SlotNSlot/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/slotnslot.eth"
icon = "facebook.png"
tags = ["News"]
