genesis_id = ""
system = "Gamerbits"
dependencies = ["Ethereum"]
icon = "gamerbits"

[token]
name = "gamerbits token"
symbol = "GBIT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Bringing crypto into Asian eSports with custom software"

[crowdsales]
start_date = "2017-07-26T00:00:00"
end_date = "2017-08-26T00:00:00"
end_date_plan = "2017-08-26T00:00:00"
genesis_address = [""]
funding_terms = "https://gbits.io/index.html"
funding_url = "https://gbits.io/crowdsale-n.html"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "gbits.io"
url = "https://gbits.io/index.html"
tags = ["Main"]

[[links]]
type = "paper"
name = "Gamerbits Whitepaper"
url = "https://gbits.io/Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Gamerbits GitHub"
url = "https://github.com/Gamerbit"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2043383"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Gamerbits_"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/gamerbitsf"
icon = "facebook.png"
tags = ["News"]
