genesis_id = ""
system = "Centra"
dependencies = ["Ethereum"]
icon = "centra"

[token]
name = "centra token"
symbol = "CTR"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Centra Card is the worlds first Multi-Blockchain Debit Card"

[crowdsales]
start_date = "2017-08-05T00:00:00"
end_date = "2017-10-05T00:00:00"
end_date_plan = "2017-10-05T00:00:00"
genesis_address = [""]
funding_terms = "https://www.centra.tech/terms-of-service/"
funding_url = "https://www.centra.tech/token-sale/"
tokens_sold = 68000000
tokens_issued = 100000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "centra.tech"
url = "https://www.centra.tech/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Centra Whitepaper"
url = "https://www.centra.tech/CentraWhitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Centra GitHub"
url = "https://github.com/CentraTech/smart-contract"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Centra Blog"
url = "https://medium.com/@Centra"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2041101"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Centra_Card"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Centra Telegram"
url = "https://t.me/centratech"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Centra Slack"
url = "https://centratech.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/CentraCard"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCGeFS7P6f6dLuwtQpZtRnuA"
icon = "youtube.png"
tags = ["News"]
