genesis_id = ""
system = "Everex"
dependencies = ["Ethereum"]
icon = "everex"

[token]
name = "everex coin"
symbol = "EVX"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Powered Microfinance & Mobile Payments"

[crowdsales]
start_date = "2017-07-24T00:00:00"
end_date = "2017-09-30T00:00:00"
end_date_plan = "2017-09-30T00:00:00"
genesis_address = [""]
funding_terms = "https://drive.google.com/file/d/0B9F9xvW65bb0bEVGazJWdXZfYkk/view"
funding_url = "https://tokensale.everex.io/#"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "everex.io"
url = "https://everex.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Everex Whitepaper"
url = "https://daks2k3a4ib2z.cloudfront.net/59157962bdb4300afa8771a9/5963c09d077a520b5a965"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Everex GitHub"
url = "https://github.com/EverexIO"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Everex Blog"
url = "https://blog.everex.io/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/everexio"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Everex Telegram"
url = "https://t.me/everexio"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Everex Slack"
url = "http://bit.ly/evxslack"
icon = "slack.png"
tags = ["News"]
