genesis_id = ""
system = "PIVX"
dependencies = ["independent"]
icon = "pivx"

[token]
name = "pivx"
symbol = "PIVX"

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = ""

[aliases]
coinmarketcap = "PIVX"


[specs]
supply = ""

[flags]

[[links]]
type = "website"
name = "pivx.org"
url = "https://pivx.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "PIVX Whitepaper"
url = "https://pivx.org/wp-content/uploads/2017/03/PIVX-purple-paper-Technincal-Notes.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "PIVX GitHub"
url = "https://github.com/PIVX-Project/PIVX"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "PIVX Blog"
url = "https://pivx.org/news/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1262920.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/_pivx"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "PIVX Slack"
url = "https://slack.pivx.org/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/pivx/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCr4Wk2opstIsUvMOz9quFSg"
icon = "youtube.png"
tags = ["News"]
