genesis_id = ""
system = "Embermine"
dependencies = ["independent"]
icon = "embermine"

[token]
name = "Embermine token"
symbol = ""

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "The Operating System for the Creative Lifestyle"

[crowdsales]
start_date = "2017-05-05T00:00:00"
end_date = "2017-06-02T00:00:00"
end_date_plan = "2017-06-02T00:00:00"
genesis_address = [""]
funding_terms = "https://embermine.com/"
funding_url = "https://embermine.com/"
tokens_sold = 50000000
tokens_issued = 150000000
btc_raised = 6
cap_limit = ["usd = 56379"]
raised = ["usd = 18494"]

[[links]]
type = "website"
name = "embermine.com"
url = "https://embermine.com/"
tags = ["Main"]


[[links]]
type = "github"
name = "Embermine GitHub"
url = "https://github.com/theembermine"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1914703.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/TheEmbermine"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Embermine Slack"
url = "https://emberminepublic.slack.com/join/shared_invite/MjA5MjE4OTM0OTQ0LTE0OTk1MzYxODItZDdkYTgzMDEyZQ"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Embermine/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/embermine"
icon = "facebook.png"
tags = ["News"]

[first_price]
btc = 0.00000013
usd = 0.00037586
date = ""
