genesis_id = ""
system = "Blocklancer"
dependencies = ["Ethereum"]
icon = "blocklancer"

[token]
name = "lancer token"
symbol = "LNC"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "First Decentralized Autonomous Jobmarket"

[crowdsales]
start_date = "2017-08-05T24:00:00"
end_date = "2017-09-05T24:00:00"
end_date_plan = "2017-09-05T24:00:00"
genesis_address = [""]
funding_terms = "https://blocklancer.net"
funding_url = "https://blocklancer.net"
tokens_sold = ""
tokens_issued = 1000000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "blocklancer.net"
url = "https://blocklancer.net/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Blocklancer Whitepaper"
url = "https://blocklancer.net/static/main/docs/lancer_whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Blocklancer GitHub"
url = "https://github.com/Blocklancer/Blocklancer-Contracts"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1974481.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/blocklancer"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/blocklancer/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/blocklancer"
icon = "facebook.png"
tags = ["News"]
