genesis_id = ""
system = "LEOCoin"
icon = "leocoin"
dependencies = ["Ethereum"]

[token]
name = "leocoin"
symbol = "LEO"

[consensus]
type = "ERC20 Token"
algorithm = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Platform for the creation and implementation of smart contracts and decentralized applications"
tags = ["DAO"]
hashtag = "#LEOCOIN"
page_state = "ready"

[aliases]
coinmarketcap = "LEOCoin"

[specs]
total_tokens = 1000000000

[[links]]
name = "leocoin.org"
url = "http://www.leocoin.org/"
type = "website"
icon = "website.png"
tags = ["Main"]

[[links]]
name = "Explorer"
url = "https://insight.leocoin.org/"
type = "explorer"
icon = "explorer.png"
tags = ["Main", "Apps", "Analytics"]

[[links]]
name = "Explorer"
url = "https://cryptobe.com/chain/LEOcoin"
type = "explorer"
icon = "explorer.png"
tags = ["Main", "Apps", "Analytics"]

[[links]]
name = "Explorer"
url = "http://blockchain.leocoin.org/"
type = "explorer"
icon = "explorer.png"
tags = ["Main", "Apps", "Analytics"]

[[links]]
name = "LEOCoin GitHub"
url = "https://github.com/Leocoin-project/LEOcoin"
type = "github"
icon = "github.png"
tags = ["Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1545712.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
name = "Twitter"
url = "https://twitter.com/LEOcoinORG"
type = "twitter"
icon = "twitter.png"
tags = ["News"]

[[links]]
name = "Ubiq blog"
url = "https://medium.com/the-ubiq-report"
type = "blog"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
name = "reddit"
url = "https://www.reddit.com/r/LEOcoinorg/"
type = "reddit"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/LEOcoin.org"
icon = "facebook.png"
tags = ["News"]

[[links]]
name = "Google+"
url = "https://plus.google.com/u/0/106893535574298107342"
type = "custom"
icon = "googleplus.png"
tags = ["News"]

[[links]]
name = "Markets CMC"
url = "https://coinmarketcap.com/currencies/leocoin/#markets"
type = "custom"
icon = "link.png"
tags = ["Apps", "Analytics"]

[[links]]
name = "Cryptopia"
url = "https://www.cryptopia.co.nz/"
type = "custom"
icon = "cryptopia.png"
tags = ["Apps", "Exchange"]

[[links]]
name = "Livecoin"
url = "https://www.livecoin.net/"
type = "custom"
icon = "livecoin.png"
tags = ["Apps", "Exchange"]

[flags]
quantum = true
