genesis_id = ""
system = "Gluon"
dependencies = ["Ethereum"]
icon = "gluon"

[token]
name = "gluon token"
symbol = "GLU"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Tokenizing the Intelligent Connected Automotive Marketplace"

[crowdsales]
start_date = "2017-08-07T00:00:00"
end_date = "2017-08-17T23:59:00"
end_date_plan = "2017-08-17T23:59:00"
genesis_address = [""]
funding_terms = "https://glutoken.com/"
funding_url = "https://glutoken.com/"
tokens_sold = ""
tokens_issued = 200000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "glutoken.com"
url = "https://glutoken.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Gluon Whitepaper"
url = "https://glutoken.com/wp-content/uploads/2017/08/Gluon-Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2059680]ANN"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/glu_token?lang=en"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Gluon Telegram"
url = "https://t.me/glutoken"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/gluonsolutions/?ref=br_rs"
icon = "facebook.png"
tags = ["News"]
