genesis_id = ""
system = "Solar DAO"
dependencies = ["Ethereum"]
icon = "solardao"

[token]
name = "solar dao token"
symbol = "SDO"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Fund designed to invest in PV solar plants"

[crowdsales]
start_date = "2016-07-27T21:00:00"
end_date = "2017-08-31T20:59:00"
end_date_plan = "2017-08-31T20:59:00"
genesis_address = [""]
funding_terms = "https://solardao.me/"
funding_url = "https://solardao.me/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = ""
raised = [""]

[[links]]
type = "website"
name = "solardao.me"
url = "https://solardao.me/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Solar DAO Whitepaper"
url = "http://solardao.me/files/wpeng.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Solar DAO GitHub"
url = "https://github.com/Solar-DAO"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Solar DAO Blog"
url = "https://medium.com/@solar.dao"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2020066"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/SolarDAO"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Solar DAO Telegram"
url = "https://t.me/solardao"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Solar DAO Slack"
url = "https://bancor-slack-invite.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Bancor/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/solar.dao/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCA125wWsdbsG1XPenWcBkyg"
icon = "youtube.png"
tags = ["News"]
