genesis_id = ""
system = "District0x"
dependencies = ["Ethereum"]
icon = "district0x"

[token]
name = "district0x token"
symbol = "DNT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Network of decentralized markets and communities"

[crowdsales]
start_date = "2017-07-18T15:00:00"
end_date = "2017-08-01T15:00:00"
end_date_plan = "2017-08-01T15:00:00"
genesis_address = [""]
funding_terms = "https://contribution.district0x.io/"
funding_url = "https://contribution.district0x.io/"
tokens_sold = 600000000
tokens_issued = 1000000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "district0x.io"
url = "https://district0x.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "District0x Whitepaper"
url = "https://district0x.io/docs/district0x-whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "District0x GitHub"
url = "https://github.com/district0x"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "District0x Blog"
url = "https://blog.district0x.io/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/district0x"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "District0x Slack"
url = "https://district0x-slack.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/district0x/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/district0x/"
icon = "facebook.png"
tags = ["News"]
