genesis_id = ""
system = "Lunyr"
dependencies = ["Ethereum"]
icon = "lunyr"

[token]
name = "lunyr token"
symbol = "LUN"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Decentralized world knowledge base"

[crowdsales]
start_date = "2017-03-29T00:00:00"
end_date = "2017-04-28T00:00:00"
end_date_plan = "2017-04-28T00:00:00"
genesis_address = ["0xfa05A73FfE78ef8f1a739473e462c54bae6567D9"]
funding_terms = "https://github.com/Lunyr/Misc/blob/master/Presale_Purchase_Agreement.pdf"
funding_url = "https://lunyr.com/"
tokens_sold = 2703356
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "lunyr.com"
url = "https://lunyr.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Lunyr Whitepaper"
url = "https://github.com/Lunyr/Lunyr/blob/master/Lunyr_White_Paper_ENG.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Lunyr GitHub"
url = "https://github.com/Lunyr/Lunyr"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Lunyr Blog"
url = "https://medium.com/lunyr"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1818468.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/LunyrInc"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Lunyr Slack"
url = "https://slack.lunyr.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Lunyr/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Lunyr-806275516194118/"
icon = "facebook.png"
tags = ["News"]
