genesis_id = ""
system = "Nexxus"
dependencies = ["independent"]
icon = "nexxus"

[token]
name = "Nexxus token"
symbol = ""

[consensus]
consensus_type = "POS"
consensus_name = "Proof-of-Stake"

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Services company for the cryptocurrency industry"

[crowdsales]
start_date = "2017-05-01T00:00:00"
end_date = "2017-06-01T00:00:00"
end_date_plan = "2017-06-01T00:00:00"
genesis_address = [""]
funding_terms = "https://www.nexxusuniversity.com/Attachments/38/21/TokenSaleTerms.pdf"
funding_url = "https://goo.gl/forms/OlLCIbLz2CxJK0HY2"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "nexxuspartners.com"
url = "http://www.nexxuspartners.com/sections/company/21/partners/index.html"
tags = ["Main"]

[[links]]
type = "paper"
name = "Nexxus Partners Whitepaper"
url = "http://www.nexxuspartners.com/sections/company/21/partners/white-paper.html"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Nexxus Partners GitHub"
url = "https://github.com/NexxusUniversity/nexxuscoin"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Nexxus Partners Blog"
url = "https://medium.com/@bobnexxus"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/nexxusreward"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Nexxus Partners Slack"
url = "https://nexxuspartners.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/NexxusRewards/"
icon = "reddit.png"
tags = ["News"]
