genesis_id = ""
system = "Ethbits iTrade"
dependencies = ["Ethereum"]
icon = "ethbits"

[token]
name = "ethbits token"
symbol = "ETB"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Cryptocurrency Copy Trading Platform"

[crowdsales]
start_date = "2017-04-15T00:00:00"
end_date = "2017-05-15T00:00:00"
end_date_plan = "2017-05-15T00:00:00"
genesis_address = [""]
funding_terms = "https://www.ethbits.com/terms"
funding_url = "https://www.ethbits.com/register"
tokens_sold = 1307752
tokens_issued = 1307752
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "ico.ethbits.com"
url = "https://ico.ethbits.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "EthBits Whitepaper"
url = "https://ico.ethbits.com/white_paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "EthBits GitHub"
url = "https://github.com/EthBits"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1834042"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/ethbits"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "EthBits Telegram"
url = "https://t.me/EthBitsChatroom"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "EthBits Slack"
url = "https://ethbits.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Ethbits/"
icon = "reddit.png"
tags = ["News"]
