genesis_id = ""
system = "Magos"
dependencies = ["Ethereum"]
icon = "magos"

[token]
name = "magos token"
symbol = "MAG"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Oracle based on Artificial Intelligence"

[crowdsales]
start_date = "2017-08-16T20:00:00"
end_date = "2017-09-30T20:00:00"
end_date_plan = "2017-09-30T20:00:00"
genesis_address = [""]
funding_terms = "https://magos.io/"
funding_url = "http://magos.io/tokens/"
tokens_sold = ""
tokens_issued = 50123377
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "magos.io"
url = "https://magos.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Magos Whitepaper"
url = "https://magos.io/bluepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Magos GitHub"
url = "https://github.com/bancorprotocol/contracts"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Magos Blog"
url = "https://medium.com/@MAGOS"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2087842"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/MagosNetwork"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Magos Telegram"
url = "https://t.me/joinchat/FVOnbQ0vvDFeHNUkvdQZzg"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Magos Slack"
url = "https://magos-invite.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Bancor/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/MAGOS.io/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCA125wWsdbsG1XPenWcBkyg"
icon = "youtube.png"
tags = ["News"]
