genesis_id = ""
system = "Edgeless"
icon = "edgeless"
dependencies = ["Ethereum"]

[token]
name = "edgeless"
symbol = "EDG"

[consensus]
type = "ERC20 Token"
algorithm = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Decentralised CASINO"
tags = ["DAO"]
hashtag = "##Edgeless"
page_state = "ready"

[aliases]
coinmarketcap = "Edgeless"

[specs]
total_tokens = 500000000

[[links]]
name = "edgeless.io"
url = "https://edgeless.io/"
type = "website"
icon = "website.png"
tags = ["Main"]

[[links]]
type = "paper"
name = "Edgeless Whitepaper"
url = "https://github.com/EdgelessCasino/White_paper/blob/master/White_Paper.pdf"
tags = ["Main", "Science"]

[[links]]
name = "Explorer"
url = "https://etherscan.io/token/Edgeless"
type = "explorer"
icon = "explorer.png"
tags = ["Main", "Apps", "Analytics"]

[[links]]
name = "Edgeless GitHub"
url = "https://github.com/EdgelessCasino/White_paper/blob/master/White_Paper.pdf"
type = "github"
icon = "github.png"
tags = ["Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1718384.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
name = "Twitter"
url = "https://twitter.com/edgelessproject"
type = "twitter"
icon = "twitter.png"
tags = ["News"]

[[links]]
name = "Edgeless blog"
url = "https://medium.com/edgeless"
type = "blog"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "slack"
name = "Edgeless Slack"
url = "https://edgelessethcasino.signup.team/"
icon = "slack.png"
tags = ["News"]

[[links]]
name = "reddit"
url = "https://www.reddit.com/r/Edgeless/"
type = "reddit"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/EdgelessCasino/?fref=ts"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Edgeless Telegram"
url = "https://t.me/joinchat/AAAAAEBTy7K9KXQcQsyozQ"
icon = "telegram.png"
tags = ["News"]

[[links]]
name = "Markets CMC"
url = "https://coinmarketcap.com/assets/edgeless/#markets"
type = "custom"
icon = "link.png"
tags = ["Apps", "Analytics"]

[[links]]
name = "Bittrex"
url = "https://bittrex.com"
type = "custom"
icon = "bittrex.png"
tags = ["Apps", "Exchange"]

[[links]]
name = "Liqui"
url = "https://liqui.io/"
type = "custom"
icon = "liqui.png"
tags = ["Apps", "Exchange"]

[flags]
quantum = true
