genesis_id = ""
system = "Mobile Go"
dependencies = ["Ethereum","Waves"]
icon = "mobilego"

[token]
name = "mobilego token"
symbol = "MGO"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Mobile Gaming Platform and Store"

[crowdsales]
start_date = "2017-04-25T13:00:00"
end_date = "2017-05-25T13:10:00"
end_date_plan = "2017-05-25T13:00:00"
genesis_address = [""]
funding_terms = "https://mobilego.io/pdf/MobileGo-Whitepaper.pdf"
funding_url = "https://ico.mobilego.io/"
tokens_sold = 70000000
tokens_issued = 100000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "mobilego.io"
url = "https://mobilego.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "MobileGo Whitepaper"
url = "https://mobilego.io/pdf/MobileGo-Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "MobileGo Blog"
url = "https://mobilego.io/blog/"
icon = "blog.png"
tags = ["News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1792451.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/MobileGoIco"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "MobileGo Telegram"
url = "https://t.me/mobilego"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "MobileGo Slack"
url = "https://gamecredits.com/slack.html"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/MobileGo/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/MobileGo-Crowdfund-1967836613444499/"
icon = "facebook.png"
tags = ["News"]
