genesis_id = ""
system = "Aventus"
dependencies = ["Ethereum"]
icon = "aventus"

[token]
name = "avent coin"
symbol = "AVT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Global standard for ticketing industry"

[crowdsales]
start_date = "2017-09-06T12:00:00"
end_date = "2017-09-12T12:00:00"
end_date_plan = "2017-09-12T12:00:00"
genesis_address = [""]
funding_terms = "https://aventus.io/"
funding_url = "https://aventus.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "aventus.io"
url = "https://aventus.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Aventus Whitepaper"
url = "https://aventus.io/doc/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Aventus GitHub"
url = "https://github.com/aventussystems/token-sale"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Aventus Blog"
url = "https://medium.com/aventus"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1955231.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/AventusSystems"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Aventus Slack"
url = "https://slack.aventus.io/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Aventus/"
icon = "reddit.png"
tags = ["News"]
