genesis_id = ""
system = "Kairos"
dependencies = ["Ethereum"]
icon = "kairos"

[token]
name = "kairos token"
symbol = "KAIROS"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "First Artificial intelligence driven ETF for block-chain assets"

[crowdsales]
start_date = "2017-07-27T13:00:00"
end_date = "2017-08-27T22:00:00"
end_date_plan = "2017-08-27T22:00:00"
genesis_address = [""]
funding_terms = "https://kairostokens.com/"
funding_url = "https://kairostokens.com/crowdsale"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "kairostokens.com"
url = "https://kairostokens.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Kairos Whitepaper"
url = "https://kairostokens.com/assets/pdf/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2049551.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/kairostokens"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Kairos Telegram"
url = "https://t.me/kairostokens"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Kairostokens"
icon = "facebook.png"
tags = ["News"]
