genesis_id = ""
system = "Kuna"
dependencies = ["Waves"]
icon = "kuna"

[token]
name = "kuna token"
symbol = "KUN"

[consensus]
consensus_type = ""
consensus_name = "Waves"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "The easiest way to buy and sell cryptocurrency in Eastern Europe"

[crowdsales]
start_date = "2017-07-28T10:10:00"
end_date = "2017-08-08T22:22:00"
end_date_plan = "2017-08-08T22:22:00"
genesis_address = [""]
funding_terms = "https://kuna.io/sco"
funding_url = "https://kuna.io/markets/kunbtc"
tokens_sold = 100000
tokens_issued = 1000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "kuna.io"
url = "https://kuna.io/?lang=en"
tags = ["Main"]

[[links]]
type = "paper"
name = "Kuna Whitepaper"
url = "https://kuna.io/sco"
tags = ["Main", "Science"]

[[links]]
type = "custom"
name = "Kuna Telegram"
url = "https://t.me/kuna_sco_eng"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2030252.0;all"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/kunabtc"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/kunaexchange"
icon = "facebook.png"
tags = ["News"]
