genesis_id = ""
system = "CoinDash"
dependencies = ["Ethereum"]
icon = "coindash"

[token]
name = "coindash token"
symbol = "CDT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Portfolio management and social trading platform"

[crowdsales]
start_date = "2017-07-16T00:00:00"
end_date = "2017-08-15T00:00:00"
end_date_plan = "2017-08-15T00:00:00"
genesis_address = [""]
funding_terms = "https://www.coindash.io/"
funding_url = "https://www.coindash.io/"
tokens_sold = ""
tokens_issued = 1000000000
btc_raised =""
cap_limit = ["usd = 12000000"]
raised = [""]

[[links]]
type = "website"
name = "coindash.io"
url = "https://www.coindash.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "CoinDash Whitepaper"
url = "https://www.coindash.io/coindash-whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Bancor GitHub"
url = "https://github.com/bancorprotocol/contracts"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1894530.msg18810057#msg18810057"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/coindashio"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "CoinDash Telegram"
url = "https://telegram.me/coindash"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "CoinDash Slack"
url = "https://coindasher-slack.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/coindash.io"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UC_CFhpZ81CxsDlva5pv1_NQ"
icon = "youtube.png"
tags = ["News"]
