genesis_id = ""
system = "U.CASH"
dependencies = ["hybrid"]
icon = "ucash"

[token]
name = "ucash token"
symbol = "XUC"

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Combining cash with digital currencies through retail locations"

[crowdsales]
start_date = "2017-09-08T00:00:00"
end_date = "2017-11-08T00:00:00"
end_date_plan = "2017-11-08T00:00:00"
genesis_address = [""]
funding_terms = "https://u.cash/ibo.html"
funding_url = "https://u.cash"
tokens_sold = ""
tokens_issued = 21000000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "u.cash"
url = "https://u.cash/"
tags = ["Main"]

[[links]]
type = "paper"
name = "U.CASH Whitepaper"
url = "https://docs.google.com/document/d/1Lvh4SEvGVHQ0Opj8wKmytMe63PxpXFgZNgIGbpIi22M/edit"
tags = ["Main", "Science"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/udotcash"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/ucash/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/udotcash"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCA125wWsdbsG1XPenWcBkyg"
icon = "youtube.png"
tags = ["News"]
