
genesis_id = ""
system = "Dala Token Sale"
dependencies = ["Ethereum"]
icon = "dalatokensale"

[token]
name = "dala token"
symbol = "DALA"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Financial platform for next 3.5 billion people"

[crowdsales]
start_date = "2017-10-25T18:00:00"
end_date = "2017-10-31T18:00:00"
end_date_plan = "2017-10-31T18:00:00"
genesis_address = [""]
funding_terms = "http://wala-tokensale-website.s3-website-eu-west-1.amazonaws.com/tokensaleterms.pdf"
funding_url = "https://tokensale.getwala.com"
tokens_sold = ""
tokens_issued = "1000000000"
btc_raised = ""
cap_limit = ["usd = 30000000"]
raised = [""]

[specs]
supply = 1000000000

[[links]]
type = "website"
name = "tokensale.getwala.com"
url = "https://tokensale.getwala.com"
tags = ["Main"]

[[links]]
type = "paper"
name = "Dala Token Sale Whitepaper"
url = "http://wala-tokensale-website.s3-website-eu-west-1.amazonaws.com/dalawhitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Dala Token Sale"
url = "https://github.com/GetDala/dala-smart-contracts"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Dala Token Sale Blog"
url = "https://blog.getwala.com/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2236876.new#new"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/getwala"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Dala Token Sale Telegram"
url = "https://t.me/getwala"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/getwala"
icon = "reddit.png"
tags = ["News"]
