genesis_id = ""
system = "Lampix"
dependencies = ["Ethereum"]
icon = "lampix"

[token]
name = "lampix token"
symbol = "PIX"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Blockchain ‘image mining’ network for augmented reality systems"

[crowdsales]
start_date = "2017-08-09T08:00:00"
end_date = "2017-08-18T09:00:00"
end_date_plan = "2017-08-18T09:00:00"
genesis_address = [""]
funding_terms = "https://www.lampix.co/index.html"
funding_url = "https://www.lampix.co/token.html"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "lampix.co"
url = "https://www.lampix.co/index.html"
tags = ["Main"]

[[links]]
type = "paper"
name = "Lampix Whitepaper"
url = "https://www.dropbox.com/s/3vs49t1dgcase9v/pix%20token%20whitepaper%20v7.docx?dl=0"
tags = ["Main", "Science"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/lampix_co"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Lampix Slack"
url = "https://lampix-invite.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "blog"
name = "Lampix Blog"
url = "https://medium.com/@lampix"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://lampix-invite.herokuapp.com/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Lampix-997463780290920/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCY3N6_p3fWC76XFrQlid0vQ"
icon = "youtube.png"
tags = ["News"]
