genesis_id = ""
system = "Asch"
dependencies = ["Ethereum"]
icon = "asch"

[token]
name = "asch token"
symbol = "XAS"

[consensus]
type = "ERC20 Token"
algorithm = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Decentralized Application Platform"
tags = ["DAO"]
page_state = "ready"

[aliases]
coinmarketcap = "Asch"
nickname = "Asch"

[[links]]
type = "website"
name = "asch.so"
url = "https://www.asch.so/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Asch Whitepaper"
url = "https://www.asch.so/asch-whitepaper-en.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Asch GitHub"
url = "https://github.com/AschPlatform"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Asch Blog"
url = "http://blog.asch.so/"
icon = "blog.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1880303.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Asch_Global"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Asch Slack"
url = "https://asch-platform.slack.com"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/AschPlatform"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/AschPlatform"
icon = "facebook.png"
