genesis_id = ""
system = "DisLedger"
dependencies = ["Ethereum"]
icon = "disLedger"

[token]
name = "disledger token"
symbol = "DCL"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Distributed Concurrence Ledgers"

[crowdsales]
start_date = "2017-09-01T12:00:00"
end_date = "2017-09-30T12:00:00"
end_date_plan = "2017-09-30T12:00:00"
genesis_address = [""]
funding_terms = "https://www.disledger.com/"
funding_url = "https://www.disledger.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "disledger.com/"
url = "https://www.disledger.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "DisLedger Whitepaper"
url = "https://www.disledger.com/DisLedger_TokenLaunch.pdf"
tags = ["Main", "Science"]

[[links]]
type = "paper"
name = "DisLedger Technical Whitepaper"
url = "https://www.disledger.com/DisLedger_Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/disledgerinfo"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "DisLedger Telegram"
url = "https://t.me/DisLedger_Official"
icon = "telegram.png"
tags = ["News"]
