genesis_id = ""
system = "Fluence"
dependencies = ["Ethereum"]
icon = "fluence"

[token]
name = "fluence token"
symbol = "FPT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized encrypted database, secured by blockchain"

[crowdsales]
start_date = "2017-08-07T13:00:00"
end_date = "2017-08-15T13:00:00"
end_date_plan = "2017-08-15T13:00:00"
genesis_address = [""]
funding_terms = "http://fluence.ai/"
funding_url = "http://fluence.ai/preico"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "fluence.ai"
url = "http://fluence.ai/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Fluence Whitepaper"
url = "https://drive.google.com/file/d/0B07gyODhPstQWjVLMlkyVjRZVE0/view"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Fluence GitHub"
url = "https://github.com/FluenceLabs"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2060630.msg20564184"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/@FluenceAI"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Fluence Telegram"
url = "https://t.me/FluenceAI"
icon = "telegram.png"
tags = ["News"]
