genesis_id = ""
system = "openZen"
dependencies = ["Ethereum"]
icon = "openzen"

[token]
name = "zen token"
symbol = "ZNT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Application which is alternative to browser"

[crowdsales]
start_date = "2017-07-31T18:00:00"
end_date = "2017-08-31T18:00:00"
end_date_plan = "2017-08-31T18:00:00"
genesis_address = [""]
funding_terms = "http://openzen.co"
funding_url = "http://openzen.co"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "openzen.co"
url = "http://openzen.co"
tags = ["Main"]

[[links]]
type = "paper"
name = "openZen Whitepaper"
url = "https://docs.google.com/document/d/1rr6jF9IcmX-sCyL-ipIOYfObyHAMV8zCv8BbZdlP0z8/edit?usp=sharing"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "openZen Blog"
url = "https://medium.com/@openzen"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "github"
name = "openZen GitHub"
url = "https://github.com/openzen"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2036653"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/JustOpenZen"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "openZen Slack"
url = "https://openzen.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/openZen/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/openZen"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "openZen Telegram"
url = "https://t.me/openzen"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/openzen"
icon = "youtube.png"
tags = ["News"]
