genesis_id = ""
system = "BitCAD"
dependencies = ["Ethereum"]
icon = "bitcad"

[token]
name = "bitcad token"
symbol = "BCD"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Encrypted Smart Platform"

[crowdsales]
start_date = "2017-04-05T12:00:00"
end_date = "2017-04-06T12:00:00"
end_date_plan = "2017-04-06T12:00:00"
genesis_address = [""]
funding_terms = "https://blog.bitcad.io/bitcad-crowdsale-details-cc45a9f320fa"
funding_url = "http://ico.bitcad.io/"
tokens_sold = 7228133
tokens_issued = 100000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "bitcad.io"
url = "http://bitcad.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "BitCAD Whitepaper"
url = "http://bitcad.io/BitCAD.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "BitCAD GitHub"
url = "https://github.com/BitCADplatform"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "BitCAD Blog"
url = "https://blog.bitcad.io/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1853784.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/bitcadplatform"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "BitCAD Telegram"
url = "https://t.me/bitcad"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "BitCAD Slack"
url = "https://bitcad.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/bitcadplatform"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCCv3pFp-K-1q-8UEnxCBPCA"
icon = "youtube.png"
tags = ["News"]
