genesis_id = ""
system = "Chain of Points"
dependencies = ["Ethereum"]
icon = "chainofpoints"

[token]
name = "point coin"
symbol = "POINt"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Transforming Loyalty into Rewards"

[crowdsales]
start_date = "2017-02-26T09:00:00"
end_date = "2017-03-02T11:59:00"
end_date_plan = "2017-03-02T11:59:00"
genesis_address = [""]
funding_terms = "https://chainofpoints.com/"
funding_url = "https://chainofpoints.com/"
tokens_sold = ""
tokens_issued = 100000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "chainofpoints.com"
url = "https://chainofpoints.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Chain of Points Whitepaper"
url = "https://chainofpoints.com/cop_whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Chain of Points Blog"
url = "https://medium.com/chainofpoints"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1773304.msg17688483"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/chainofpoints"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/chainofpoints"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Chain of Points Slack"
url = "https://chainofpoints.slack.com/"
icon = "slack.png"
tags = ["News"]
