genesis_id = ""
system = "Bits Digit"
dependencies = ["Ethereum"]
icon = "bitsdigit"

[token]
name = "bits digit token"
symbol = "BITSD"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "One Solution for all needs "

[crowdsales]
start_date = "2017-08-01T00:00:00"
end_date = "2017-08-31T00:00:00"
end_date_plan = "2017-08-31T00:00:000"
genesis_address = [""]
funding_terms = "https://bitsdigit.com/BITSD_Disclaimer.pdf"
funding_url = "https://bitsdigit.com/"
tokens_sold = ""
tokens_issued = 700000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "bitsdigit.com"
url = "https://bitsdigit.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Bits Digit Whitepaper"
url = "https://bitsdigit.com/Whitepaper_bitsdigit.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Bits Digit GitHub"
url = "https://github.com/bitsdigit"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2024852.new"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/user/bitsdigit"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/bitsdigit"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Bits Digit Telegram"
url = "https://t.me/bitsd"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/bitsdigit"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/c/bitsdigit"
icon = "youtube.png"
tags = ["News"]
