genesis_id = ""
system = "Monkey Capital"
dependencies = ["Waves"]
icon = "monkeycapital"

[token]
name = "monkey capital token"
symbol = "MNY"

[consensus]
consensus_type = ""
consensus_name = "Wave"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "A decentralised Hedge Fund"

[crowdsales]
start_date = "2017-08-08T16:00:00"
end_date = "2017-09-09T16:00:00"
end_date_plan = "2017-09-09T16:00:00"
genesis_address = [""]
funding_terms = "https://www.monkey.capital/"
funding_url = "https://www.monkey.capital/"
tokens_sold = ""
tokens_issued = 1000000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "monkey.capital"
url = "https://www.monkey.capital/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Monkey Capital Whitepaper"
url = "https://www.monkey.capital/docs/MC_Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2003741"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/monkeycapitaico"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Monkey Capital Slack"
url = "https://monkeycapital.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/monkeycapital/"
icon = "reddit.png"
tags = ["News"]
