genesis_id = ""
system = "Trackr"
dependencies = ["Ethereum"]
icon = "trackr"

[token]
name = "trackr token"
symbol = "TKR"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Crypto app for portfolio management"

[crowdsales]
start_date = "2017-08-16T12:00:00"
end_date = "2017-09-15T12:00:00"
end_date_plan = "2017-09-15T12:00:00"
genesis_address = ["0xA971AfDCa01BD1ca1499346E730a3d1Dc06a3A9d"]
funding_terms = "https://www.trackr.im/"
funding_url = "https://www.trackr.im/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "trackr.im"
url = "https://www.trackr.im/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Trackr Whitepaper"
url = "https://www.trackr.im/media/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Trackr GitHub"
url = "https://github.com/trackr-im/"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Trackr Blog"
url = "https://medium.com/@trackr.im/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2046549"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/trackrim"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Trackr Slack"
url = "http://slack.trackr.online/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/trackrim"
icon = "facebook.png"
tags = ["News"]
