genesis_id = ""
system = "Neuromation"
dependencies = ["Ethereum"]
icon = "neuromation"

[token]
name = "neuromation token"
symbol = ""

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Distributed computing platform for deep learning application"

[crowdsales]
start_date = "2017-11-28T00:00:00"
end_date = "2018-01-01T00:00:00"
end_date_plan = "2018-01-01T00:00:00"
genesis_address = [""]
funding_terms = "https://neuromation.cryptonomos.com/neuromation-whitepaper.pdf"
funding_url = "https://neuromation.cryptonomos.com/neuromation-whitepaper.pdf"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "neuromation.cryptonomos.com"
url = "https://neuromation.cryptonomos.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Neuromation Whitepaper"
url = "https://neuromation.cryptonomos.com/neuromation-whitepaper.pdf"
tags = ["Main", "Science"]