genesis_id = ""
system = "AdEx"
dependencies = ["Ethereum"]
icon = "adex"

[token]
name = "adex token"
symbol = "ADX"

[consensus]
type = "ERC20 Token"
algorithm = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Blockchain-based ad exchange aiming"

[crowdsales]
start_date = "2017-06-30T09:00:00"
end_date = "2017-07-30T09:00:00"
end_date_plan = "2017-07-30T09:00:00"
genesis_address = ["0x4470BB87d77b963A013DB939BE332f927f2b992e"]
funding_terms = "https://www.adex.network/"
funding_url = "https://www.adex.network/"
tokens_sold = 80000000
tokens_issued = 100000000
btc_raised = 4967
cap_limit = [""]
raised = ["usd = 12578363"]

[aliases]
coinmarketcap = "AdEx"
nickname = "AdEx"

[[links]]
type = "website"
name = "adex.network"
url = "https://www.adex.network/"
tags = ["Main"]

[[links]]
type = "paper"
name = "AdEx Whitepaper"
url = "https://www.adex.network/adex/AdEx-Whitepaper-v.7.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "AdEx GitHub"
url = "https://github.com/AdExBlockchain"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "AdEx Blog"
url = "https://medium.com/the-adex-blog"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1965467.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/AdEx_Network"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "AdEx Telegram"
url = "https://t.me/AdExNetwork"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "AdEx Slack"
url = "https://neosmarteconomy.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/AdEx/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/AdExNetwork/"
icon = "facebook.png"
