genesis_id = ""
system = "Suretly"
dependencies = ["Ethereum","Waves"]
icon = "suretly"

[token]
name = "suretly token"
symbol = "SUR"

[consensus]
consensus_type = "ERC20 & Waves Asset"
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "First crowdvouching platform"

[crowdsales]
start_date = "2017-07-11T08:00:00"
end_date = "2017-08-11T08:00:00"
end_date_plan = "2017-08-11T08:00:00"
genesis_address = [""]
funding_terms = "https://www.ico.suretly.com/"
funding_url = "https://www.ico.suretly.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = 128
cap_limit = ["usd = 10000000"]
raised = ["usd = 1151148"]

[[links]]
type = "website"
name = "ico.suretly.com"
url = "https://www.ico.suretly.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Suretly Whitepaper"
url = "https://suretly.com/docs/Suretly_whitepaper_v1.2.pdf"
tags = ["Main", "Science"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1879035.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/suretly_com"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Suretly Slack"
url = "https://suretly.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://urbancrypto.com/suretly-crowdvouching-platform/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/suretly/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UC5yutn5ceZHgKZxWUQ-WLwQ"
icon = "youtube.png"
tags = ["News"]
