genesis_id = ""
system = "Bancor"
dependencies = ["Ethereum"]
icon = "bancor"

[token]
name = "bancor token"
symbol = "BNT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Network of Intrinsically Tradeable Smart Tokens"

[aliases]
coinmarketcap = "Bancor"

[crowdsales]
start_date = "2017-06-12T10:00:00"
end_date = "2017-06-25T14:00:00"
end_date_plan = "2017-06-25T14:00:00"
genesis_address = [""]
funding_terms = "https://bancor.network/"
funding_url = "https://bancor.network/fundraiser"
tokens_sold = 39661989
tokens_issued = 79323978
btc_raised = 55990
cap_limit = ["usd = 306490147"]
raised = ["usd = 153245073"]

[[links]]
type = "website"
name = "bancor.network"
url = "https://bancor.network/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Bancor Whitepaper"
url = "https://www.bancor.network/whitepaper/en"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Bancor GitHub"
url = "https://github.com/bancorprotocol/contracts"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Bancor Blog"
url = "https://blog.bancor.network/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1789222.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/bancornetwork"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Bancor Telegram"
url = "https://t.me/bancor"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Bancor Slack"
url = "https://bancor-slack-invite.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Bancor/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/bancor/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCA125wWsdbsG1XPenWcBkyg"
icon = "youtube.png"
tags = ["News"]

[first_price]
btc = 0.00141168
usd = 3.86377681
date = ""
