genesis_id = ""
system = "Coss"
dependencies = ["Ethereum"]
icon = "coss"

[token]
name = "coss token"
symbol = "COSS"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Crypto One Stop Solution platform"

[crowdsales]
start_date = "2017-08-08T12:08:00"
end_date = "2017-09-06T12:08:00"
end_date_plan = "2017-09-06T12:08:00"
genesis_address = [""]
funding_terms = "https://coss.io"
funding_url = "https://coss.io/ico"
tokens_sold = 130000000
tokens_issued = 200000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "coss.io"
url = "https://coss.io"
tags = ["Main"]

[[links]]
type = "paper"
name = "Coss Whitepaper"
url = "https://www.coss.io/documents/coss-whitepaper-v3.pdf"
tags = ["Main", "Science"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2050735.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/cosscrypto"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Coss Slack"
url = "https://cosstokenswap.slack.com/join/shared_invite/MjA0NDA2MjY4MzUzLTE0OTg2NjMxNDktOTkxZDcwOTYxYQ"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/cosscrypto/"
icon = "facebook.png"
tags = ["News"]
