genesis_id = ""
system = "Umbrella Coin"
dependencies = ["Ethereum"]
icon = "umbrellacoin"

[token]
name = "umbrellacoin token"
symbol = "UMC"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized, Democratized Insurance Platform"

[crowdsales]
start_date = "2017-06-12T10:00:00"
end_date = "2017-06-25T14:00:00"
end_date_plan = "2017-06-25T14:00:00"
genesis_address = [""]
funding_terms = "https://www.umbrellacoin.org/"
funding_url = "https://www.umbrellacoin.org/crowdfund"
tokens_sold = ""
tokens_issued = 100000000
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "umbrellacoin.org"
url = "https://www.umbrellacoin.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Umbrella Coin Whitepaper"
url = "https://github.com/umbrellacoin/umc/blob/master/documents/UMC.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Umbrella Coin GitHub"
url = "https://github.com/umbrellacoin"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Umbrella Coin Blog"
url = "https://medium.com/@umbrellacoin"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1789222.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/umbrellacoin"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/UmbrellaCoin/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/umbrellacoin/?ref=page_internal"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCqdy_X_sXz1jK7D8fFDlX7Q"
icon = "youtube.png"
tags = ["News"]
