genesis_id = ""
system = "TenX"
dependencies = ["independent"]
icon = "tenx"

[token]
name = "tenx token"
symbol = "PAY"

[consensus]
type = ""
algorithm = ""

[aliases]
coinmarketcap = "TenX"
nickname = "TenX"

[descriptions]
state = "Public"
system_type = "cryptocurrency"
headline = "Making Cryptocurrencies Spendable Anytime Anywhere"
tags = ["DAO"]
page_state = "ready"

[[links]]
type = "website"
name = "tenx.tech"
url = "https://www.tenx.tech/"
tags = ["Main"]

[[links]]
type = "paper"
name = "TenX Whitepaper"
url = "https://www.tenx.tech/whitepaper/tenx_whitepaper_final.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "TenX Blog"
url = "https://medium.com/@TenX/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1953612.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/tenxwallet"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "TenX Slack"
url = "https://ten-x.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/TenX/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/tenxwallet/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCrh49JX-9UQJbee6e4EGhog"
icon = "youtube.png"
tags = ["News"]
